#include <catch2/catch.hpp>

#include "libslic3r/Config.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/PrintConfig.hpp"

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <sstream>
#include <string>

using namespace Slic3r;

namespace {

boost::filesystem::path write_temp_gcode(const std::string &name, const std::string &contents)
{
    const boost::filesystem::path dir = boost::filesystem::temp_directory_path() / "edgeslicer_tests";
    boost::filesystem::create_directories(dir);
    const boost::filesystem::path path = dir / name;
    boost::nowide::ofstream ofs(path.string());
    ofs << contents;
    return path;
}

std::string thumbnail_block()
{
    return "; THUMBNAIL_BLOCK_START\n"
           "\n"
           "\n"
           "; thumbnail begin 48x48 4\n"
           "; QUJD\n"
           "; thumbnail end\n"
           "; THUMBNAIL_BLOCK_END\n";
}

std::string config_block_with_filaments(const std::string &filament_diameter)
{
    // load_from_gcode_file rejects blocks with fewer than 80 key/value pairs.
    // Repeat a known-good key so we clear that floor without round-tripping every
    // PrintConfig value (some serialize to forms that fail deserialize).
    std::ostringstream oss;
    oss << "; CONFIG_BLOCK_START\n";
    oss << "; filament_diameter = " << filament_diameter << "\n";
    for (int i = 0; i < 80; ++i)
        oss << "; layer_height = 0.2\n";
    oss << "; CONFIG_BLOCK_END\n";
    return oss.str();
}

} // namespace

TEST_CASE("load_from_gcode_file accepts an upstream OrcaSlicer producer header", "[Config][GCodeImport]")
{
    // Header recognized, but no CONFIG_BLOCK: proves the producer whitelist accepted the
    // line instead of aborting with "Not a gcode file generated by ...".
    const auto path = write_temp_gcode("orca_header.gcode",
        "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00 UTC\n"
        "G28\n");
    DynamicPrintConfig config = DynamicPrintConfig::full_print_config();
    REQUIRE_THROWS_WITH(config.load_from_gcode_file(path.string(), ForwardCompatibilitySubstitutionRule::EnableSilent),
                        Catch::Matchers::Contains("CONFIG_BLOCK_START"));
    boost::filesystem::remove(path);
}

TEST_CASE("load_from_gcode_file still rejects an unknown producer header", "[Config][GCodeImport]")
{
    const auto path = write_temp_gcode("cura_header.gcode",
        "; generated by Cura_SteamEngine 5.0\n"
        "G28\n");
    DynamicPrintConfig config = DynamicPrintConfig::full_print_config();
    REQUIRE_THROWS_WITH(config.load_from_gcode_file(path.string(), ForwardCompatibilitySubstitutionRule::EnableSilent),
                        Catch::Matchers::Contains("Not a gcode file generated by"));
    boost::filesystem::remove(path);
}

TEST_CASE("load_from_gcode_file skips extra thumbnail blocks instead of aborting", "[Config][GCodeImport]")
{
    // thumb0/thumb1 are defined in PrintConfigDef; a third block used to throw
    // UnknownOptionException ("thumb2") and abort the import. After Snapmaker #743
    // it is skipped. The defined blocks are deserialized even though they are not
    // pre-instantiated on DynamicPrintConfig.
    std::ostringstream gcode;
    gcode << "; generated by OrcaSlicer 2.4.2\n";
    gcode << thumbnail_block();
    gcode << thumbnail_block();
    gcode << thumbnail_block();
    gcode << config_block_with_filaments("1.75");

    const auto           path   = write_temp_gcode("orca_thumbs.gcode", gcode.str());
    DynamicPrintConfig   config = DynamicPrintConfig::full_print_config();
    REQUIRE_FALSE(config.has("thumb2"));
    REQUIRE_NOTHROW(config.load_from_gcode_file(path.string(), ForwardCompatibilitySubstitutionRule::EnableSilent));
    REQUIRE(config.has("thumb0"));
    REQUIRE(config.has("thumb1"));
    REQUIRE_FALSE(config.has("thumb2"));
    boost::filesystem::remove(path);
}

TEST_CASE("GCodeProcessor applies config from upstream OrcaSlicer gcode", "[GCodeProcessor][GCodeImport]")
{
    std::ostringstream gcode;
    gcode << "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00 UTC\n";
    gcode << config_block_with_filaments("1.75,1.75,1.75");
    gcode << "T0\nG1 X10 Y10 E0.1\nT1\nG1 X20 Y20 E0.2\nT2\nG1 X30 Y30 E0.3\n";

    const auto path = write_temp_gcode("orca_multicolor.gcode", gcode.str());
    GCodeProcessor processor;
    REQUIRE_NOTHROW(processor.process_file(path.string()));
    CHECK(processor.get_result().extruders_count == 3);
    boost::filesystem::remove(path);
}

TEST_CASE("GCodeProcessor leaves extruders_count at 0 for an unrecognized producer", "[GCodeProcessor][GCodeImport]")
{
    std::ostringstream gcode;
    gcode << "; generated by Cura_SteamEngine 5.0\n";
    gcode << config_block_with_filaments("1.75,1.75,1.75");
    gcode << "T0\nG1 X10 Y10 E0.1\nT1\nG1 X20 Y20 E0.2\n";

    const auto path = write_temp_gcode("cura_multicolor.gcode", gcode.str());
    GCodeProcessor processor;
    REQUIRE_NOTHROW(processor.process_file(path.string()));
    CHECK(processor.get_result().extruders_count == 0);
    boost::filesystem::remove(path);
}
