#include <catch2/catch.hpp>

#include "libslic3r/CostEstimate.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <sstream>
#include <string>

using namespace Slic3r;
using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;

// libslic3r/CostEstimate: the cost breakdown shown after slicing (filament per slot split into
// model / support / flush / tower, machine time, total), computed from GCodeProcessorResult only.

namespace {

using Mode = PrintEstimatedStatistics::ETimeMode;

// Three filaments: 0 prints the model (flush + tower too), 1 prints the support (+ a little model,
// flush and tower), 2 is unpriced and only primes the tower. Volumes in mm3.
void fill_three_filaments(GCodeProcessorResult &r)
{
    r.reset();
    r.extruders_count    = 3;
    r.filament_densities = { 1.24f, 1.27f, 1.0f };
    r.filament_costs     = { 20.f, 30.f, 0.f };
    r.has_filament_costs = true;
    r.time_cost          = 1.5;
    r.has_time_cost      = true;
    auto &ps = r.print_statistics;
    ps.modes[static_cast<size_t>(Mode::Normal)].time = 7200.f;   // 2 h
    ps.model_volumes_per_extruder      = { { 0, 10000. }, { 1, 2000. } };
    ps.support_volumes_per_extruder    = { { 1, 500. } };
    ps.flush_per_filament              = { { 0, 300. }, { 1, 200. } };
    ps.wipe_tower_volumes_per_extruder = { { 0, 100. }, { 1, 100. }, { 2, 50. } };
    ps.total_volumes_per_extruder      = { { 0, 10400. }, { 1, 2800. }, { 2, 50. } };
}

// GCode.cpp's update_print_estimated_stats() before CostEstimate: every filament's total volume
// times density and price, plus time_cost per hour of the Normal-mode time.
double old_total_cost(const GCodeProcessorResult &r)
{
    double total = 0.;
    for (const auto &[slot, volume] : r.print_statistics.total_volumes_per_extruder) {
        const double weight = volume * double(r.filament_densities[slot]) * 0.001;
        total += weight * double(r.filament_costs[slot]) * 0.001;
    }
    return total + r.time_cost * (r.print_statistics.modes[static_cast<size_t>(Mode::Normal)].time / 3600.0);
}

// A G-code file in a directory of its own (random name, so repeated or parallel runs never share
// one), removed when it goes out of scope. Removal never throws: a file Windows still holds open
// for a moment (virus scanner, indexer) is left behind rather than failing the test.
class TempGcode
{
public:
    TempGcode(const std::string &name, const std::string &contents)
        : m_dir(boost::filesystem::temp_directory_path() / boost::filesystem::unique_path("edgeslicer_tests_%%%%-%%%%-%%%%"))
    {
        boost::filesystem::create_directories(m_dir);
        m_path = m_dir / name;
        boost::nowide::ofstream ofs(m_path.string());
        ofs << contents;
    }
    ~TempGcode()
    {
        boost::system::error_code ec;
        boost::filesystem::remove_all(m_dir, ec);
    }
    TempGcode(const TempGcode &)            = delete;
    TempGcode &operator=(const TempGcode &) = delete;

    std::string path() const { return m_path.string(); }

private:
    boost::filesystem::path m_dir;
    boost::filesystem::path m_path;
};

// A G-code as EdgeSlicer writes it for a non-Bambu printer: config block at the end. The loader
// wants at least 80 key / value pairs in the block.
std::string gcode_with_config(const std::string &extra_keys)
{
    std::ostringstream oss;
    oss << "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00 UTC\n";
    oss << "G28\nG92 E0\nG1 X10 Y10 F3000\nG1 X60 Y10 E2.0 F1200\nG1 X60 Y60 E4.0\n";
    oss << "; CONFIG_BLOCK_START\n";
    oss << "; filament_diameter = 1.75\n";
    oss << "; filament_density = 1.24\n";
    oss << extra_keys;
    for (int i = 0; i < 80; ++i)
        oss << "; layer_height = 0.2\n";
    oss << "; CONFIG_BLOCK_END\n";
    return oss.str();
}

} // namespace

TEST_CASE("Cost breakdown splits filament cost per slot and adds machine time", "[CostEstimate]")
{
    GCodeProcessorResult r;
    fill_three_filaments(r);
    const CostBreakdown c = compute_cost(r);

    REQUIRE(c.prices_known);
    REQUIRE(c.lines.size() == 3);

    const FilamentCostLine &a = c.lines[0];
    CHECK(a.slot == 0);
    CHECK_THAT(a.model_g, WithinRel(12.4, 1e-6));
    CHECK_THAT(a.flush_g, WithinRel(0.372, 1e-6));
    CHECK_THAT(a.tower_g, WithinRel(0.124, 1e-6));
    CHECK_THAT(a.support_g, WithinAbs(0., 1e-12));
    CHECK_THAT(a.total_g, WithinRel(12.896, 1e-6));
    CHECK_THAT(a.price_per_kg, WithinRel(20., 1e-6));
    CHECK_THAT(a.model_cost, WithinRel(0.248, 1e-6));
    CHECK_THAT(a.flush_cost, WithinRel(0.00744, 1e-6));
    CHECK_THAT(a.tower_cost, WithinRel(0.00248, 1e-6));
    CHECK_THAT(a.total_cost, WithinRel(0.25792, 1e-6));

    // Support on its own filament: its cost is that filament's price.
    const FilamentCostLine &b = c.lines[1];
    CHECK(b.slot == 1);
    CHECK_THAT(b.support_g, WithinRel(0.635, 1e-6));
    CHECK_THAT(b.support_cost, WithinRel(0.01905, 1e-6));
    CHECK_THAT(b.total_cost, WithinRel(0.10668, 1e-6));

    // An unpriced filament is listed with its grams and costs nothing.
    const FilamentCostLine &z = c.lines[2];
    CHECK(z.slot == 2);
    CHECK_THAT(z.total_g, WithinRel(0.05, 1e-6));
    CHECK_THAT(z.total_cost, WithinAbs(0., 1e-12));

    CHECK_THAT(c.material, WithinRel(0.3646, 1e-6));
    CHECK_THAT(c.print_time_s, WithinRel(7200., 1e-9));
    CHECK_THAT(c.machine_rate_per_h, WithinRel(1.5, 1e-9));
    CHECK_THAT(c.machine, WithinRel(3.0, 1e-9));
    CHECK_THAT(c.total, WithinRel(3.3646, 1e-6));
    CHECK(c.any_price_set());

    // Leaves rounded to cents, totals are sums of rounded leaves.
    CHECK_THAT(c.display_material, WithinAbs(0.37, 1e-9));
    CHECK_THAT(c.display_machine, WithinAbs(3.00, 1e-9));
    CHECK_THAT(c.display_total, WithinAbs(3.37, 1e-9));
}

TEST_CASE("Cost breakdown total equals the pre-CostEstimate statistics formula", "[CostEstimate]")
{
    GCodeProcessorResult r;
    fill_three_filaments(r);
    CHECK_THAT(compute_cost(r).total, WithinRel(old_total_cost(r), 1e-9));

    // And with a single filament, no machine rate.
    r.reset();
    r.extruders_count    = 1;
    r.filament_densities = { 1.24f };
    r.filament_costs     = { 24.99f };
    r.has_filament_costs = true;
    r.time_cost          = 0.;
    r.print_statistics.modes[static_cast<size_t>(Mode::Normal)].time = 3725.f;
    r.print_statistics.model_volumes_per_extruder = { { 0, 12345.6 } };
    r.print_statistics.total_volumes_per_extruder = { { 0, 12345.6 } };
    CHECK_THAT(compute_cost(r).total, WithinRel(old_total_cost(r), 1e-9));
}

TEST_CASE("Cost breakdown with no machine rate has no machine cost", "[CostEstimate]")
{
    GCodeProcessorResult r;
    fill_three_filaments(r);
    r.time_cost = 0.;
    const CostBreakdown c = compute_cost(r);
    CHECK_THAT(c.machine, WithinAbs(0., 1e-12));
    CHECK_THAT(c.display_machine, WithinAbs(0., 1e-12));
    CHECK_THAT(c.total, WithinRel(c.material, 1e-12));
    CHECK_THAT(c.print_time_s, WithinRel(7200., 1e-9));
}

TEST_CASE("Cost breakdown without filament prices keeps machine time and flags the material unknown", "[CostEstimate]")
{
    GCodeProcessorResult r;
    fill_three_filaments(r);
    // A G-code exported with "Include filament prices in exported G-code" off: the processor's
    // fallback prices must not turn into a material cost.
    r.has_filament_costs = false;
    r.filament_costs     = { 29.99f, 29.99f, 29.99f };
    const CostBreakdown c = compute_cost(r);
    CHECK_FALSE(c.prices_known);
    CHECK_FALSE(c.any_price_set());
    REQUIRE(c.lines.size() == 3);   // grams are still known
    CHECK_THAT(c.lines[0].total_g, WithinRel(12.896, 1e-6));
    CHECK_THAT(c.material, WithinAbs(0., 1e-12));
    CHECK_THAT(c.machine, WithinRel(3.0, 1e-9));
    CHECK_THAT(c.total, WithinRel(3.0, 1e-9));
}

TEST_CASE("Cost breakdown of an empty result is empty", "[CostEstimate]")
{
    GCodeProcessorResult r;
    r.reset();
    // PrintEstimatedStatistics::reset() resets copies of the modes, so a fresh result's times are
    // whatever was in memory; GCodeProcessor sets them. Do the same here.
    r.print_statistics.modes[static_cast<size_t>(Mode::Normal)].time = 0.f;
    const CostBreakdown c = compute_cost(r);
    CHECK(c.lines.empty());
    CHECK(c.empty());
    CHECK_THAT(c.total, WithinAbs(0., 1e-12));
}

TEST_CASE("Money rounding is half away from zero", "[CostEstimate]")
{
    CHECK_THAT(round_money(0.125), WithinAbs(0.13, 1e-12));
    CHECK_THAT(round_money(1.005), WithinAbs(1.01, 1e-12));
    CHECK_THAT(round_money(2.344), WithinAbs(2.34, 1e-12));
    CHECK_THAT(round_money(-0.125), WithinAbs(-0.13, 1e-12));
    CHECK_THAT(round_money(0.), WithinAbs(0., 1e-12));
}

TEST_CASE("Summing plates adds rounded plate totals and merges filament slots", "[CostEstimate]")
{
    GCodeProcessorResult r1, r2;
    fill_three_filaments(r1);
    fill_three_filaments(r2);
    r2.time_cost = 1.5;
    r2.print_statistics.modes[static_cast<size_t>(Mode::Normal)].time = 1800.f;   // 0.5 h
    r2.print_statistics.total_volumes_per_extruder = { { 0, 1001. } };
    r2.print_statistics.model_volumes_per_extruder = { { 0, 1001. } };
    r2.print_statistics.support_volumes_per_extruder.clear();
    r2.print_statistics.flush_per_filament.clear();
    r2.print_statistics.wipe_tower_volumes_per_extruder.clear();

    const CostBreakdown p1 = compute_cost(r1);
    const CostBreakdown p2 = compute_cost(r2);
    const CostBreakdown all = sum_costs({ p1, p2 });

    CHECK(all.plates == 2);
    CHECK(all.prices_known);
    CHECK_THAT(all.display_total, WithinAbs(p1.display_total + p2.display_total, 1e-9));
    CHECK_THAT(all.display_material, WithinAbs(p1.display_material + p2.display_material, 1e-9));
    CHECK_THAT(all.display_machine, WithinAbs(p1.display_machine + p2.display_machine, 1e-9));
    CHECK_THAT(all.print_time_s, WithinRel(9000., 1e-9));
    CHECK_THAT(all.machine_rate_per_h, WithinRel(1.5, 1e-9));
    CHECK_FALSE(all.machine_rate_varies);
    REQUIRE(all.lines.size() == 3);
    CHECK_THAT(all.lines[0].total_g, WithinRel(p1.lines[0].total_g + p2.lines[0].total_g, 1e-12));
    CHECK_THAT(all.lines[0].price_per_kg, WithinRel(20., 1e-6));

    SECTION("plates on printers with different rates") {
        r2.time_cost = 3.;
        const CostBreakdown mixed = sum_costs({ p1, compute_cost(r2) });
        CHECK(mixed.machine_rate_varies);
        CHECK_THAT(mixed.machine, WithinRel(3.0 + 1.5, 1e-9));
    }
    SECTION("one plate without a machine rate makes the sum's rate unknown") {
        r2.has_time_cost = false;
        CHECK_FALSE(sum_costs({ p1, compute_cost(r2) }).machine_rate_known);
        CHECK(all.machine_rate_known);
    }
    SECTION("one plate without prices makes the sum's material unknown") {
        r2.has_filament_costs = false;
        CHECK_FALSE(sum_costs({ p1, compute_cost(r2) }).prices_known);
    }
}

TEST_CASE("GCodeProcessor reads time_cost and filament_cost from a G-code config block", "[CostEstimate][GCodeProcessor][GCodeImport]")
{
    const TempGcode gcode("cost_with_prices.gcode",
                          gcode_with_config("; filament_cost = 25\n; time_cost = 2.5\n"));
    GCodeProcessor processor;
    REQUIRE_NOTHROW(processor.process_file(gcode.path()));
    const GCodeProcessorResult &r = processor.get_result();
    CHECK(r.has_filament_costs);
    REQUIRE_FALSE(r.filament_costs.empty());
    CHECK_THAT(double(r.filament_costs[0]), WithinRel(25., 1e-6));
    CHECK_THAT(r.time_cost, WithinRel(2.5, 1e-9));
    const CostBreakdown c = compute_cost(r);
    CHECK(c.prices_known);
    CHECK(c.material > 0.);
}

TEST_CASE("GCodeProcessor reports missing filament prices instead of inventing them", "[CostEstimate][GCodeProcessor][GCodeImport]")
{
    // Exported with filament prices left out: no filament_cost key, time_cost still there.
    const TempGcode gcode("cost_without_prices.gcode", gcode_with_config("; time_cost = 2\n"));
    GCodeProcessor processor;
    REQUIRE_NOTHROW(processor.process_file(gcode.path()));
    const GCodeProcessorResult &r = processor.get_result();
    CHECK_FALSE(r.has_filament_costs);
    for (float price : r.filament_costs)
        CHECK_THAT(double(price), WithinAbs(0., 1e-12));
    CHECK_THAT(r.time_cost, WithinRel(2., 1e-9));
    const CostBreakdown c = compute_cost(r);
    CHECK_FALSE(c.prices_known);
    CHECK_THAT(c.material, WithinAbs(0., 1e-12));

    // Neither key (an older or foreign file): no machine rate either.
    const TempGcode gcode2("cost_without_any.gcode", gcode_with_config(""));
    GCodeProcessor processor2;
    REQUIRE_NOTHROW(processor2.process_file(gcode2.path()));
    CHECK_FALSE(processor2.get_result().has_filament_costs);
    CHECK_THAT(processor2.get_result().time_cost, WithinAbs(0., 1e-12));
    // The machine part is reported unknown, not as a rate of 0.
    CHECK_FALSE(processor2.get_result().has_time_cost);
    const CostBreakdown none = compute_cost(processor2.get_result());
    CHECK_FALSE(none.machine_rate_known);
    CHECK_THAT(none.machine, WithinAbs(0., 1e-12));
}
