// Adaptive pressure advance must not depend on how the layer pipeline is scheduled.
//
// A tool change used to reset AdaptivePAProcessor's last PA from the G-code generator thread while
// the processor filter was reading and writing the same value on an earlier layer. Which layer the
// reset landed in depended on thread timing, so the M900s around tool changes moved from one slice
// to the next. Tool changes now put the reset in the layer G-code (AdaptivePAProcessor::reset_marker)
// and the processor applies it in G-code order.
//
// Negative control: with GCode::reset_adaptive_pa() calling m_pa_processor->resetPreviousPA()
// unconditionally (the old behaviour), the "Prev PA" tracking check below fails.

#include <catch2/catch.hpp>

#include <cmath>
#include <cstdlib>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

#include <tbb/global_control.h>

#include "libslic3r/Model.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "test_data.hpp"

using namespace Slic3r;
using namespace Slic3r::Test;

namespace {

// Nominal PA per filament, deliberately far from anything the models below predict, so a reset
// that lands on the wrong side of a tool change shows up as a PA mismatch.
const std::vector<double> NOMINAL_PA = {0.1, 0.2};

std::string slice_two_filaments(bool bbl, bool adaptive = true)
{
    DynamicPrintConfig config = DynamicPrintConfig::full_print_config();
    config.set_num_extruders(2);
    config.set_num_filaments(2);
    config.option<ConfigOptionFloats>("filament_diameter")->values = {1.75, 1.75};
    config.option<ConfigOptionFloats>("nozzle_diameter")->values   = {0.4, 0.4};
    config.option<ConfigOptionStrings>("filament_colour")->values  = {"#FF0000", "#0000FF"};
    config.option<ConfigOptionBool>("enable_prime_tower")->value   = true;
    config.option<ConfigOptionBool>("enable_support")->value       = false;
    config.option<ConfigOptionBool>("spiral_mode")->value          = false;
    config.option<ConfigOptionFloats>("wipe_tower_x")->values      = {15.};
    config.option<ConfigOptionFloats>("wipe_tower_y")->values      = {15.};
    config.option<ConfigOptionFloat>("prime_tower_width")->value   = 35.;
    config.option<ConfigOptionBools>("enable_pressure_advance")->values   = {true, true};
    config.option<ConfigOptionBools>("adaptive_pressure_advance")->values = {adaptive, adaptive};
    config.option<ConfigOptionFloats>("pressure_advance")->values         = NOMINAL_PA;
    config.option<ConfigOptionStrings>("adaptive_pressure_advance_model")->values = {
        "0.060,2,1000\n0.050,8,1000\n0.040,16,1000\n0.050,2,10000\n0.040,8,10000\n0.030,16,10000",
        "0.045,2,1000\n0.038,8,1000\n0.031,16,1000\n0.036,2,10000\n0.029,8,10000\n0.022,16,10000"};
    // The processor writes its working ("; APA Prev PA: ... New PA: ...") as comments.
    config.option<ConfigOptionBool>("gcode_comments")->value = true;
    config.set_deserialize_strict({{"brim_type", "no_brim"}, {"skirt_loops", "0"}, {"wipe_tower_wall_type", "rectangle"}});

    Print print;
    Model model;
    ModelObject *first = model.add_object();
    first->name        = "cube-a.stl";
    first->add_volume(mesh(TestMesh::cube_20x20x20));
    first->add_instance()->set_offset(Vec3d(80., 40., 0.));
    first->ensure_on_bed();
    ModelObject *second = model.add_object();
    second->name        = "cube-b.stl";
    second->add_volume(mesh(TestMesh::cube_20x20x20));
    second->add_instance()->set_offset(Vec3d(120., 40., 0.));
    second->ensure_on_bed();
    second->volumes.front()->config.set("extruder", 2);

    print.apply(model, config);
    print.is_BBL_printer() = bbl;
    REQUIRE(print.has_wipe_tower());
    return Test::gcode(print);
}

// Drops what legitimately differs between two slices of the same plate in one process: the
// header timestamp and the object label ids (ObjectIDs keep counting across Models).
std::string normalized(const std::string &gcode)
{
    std::istringstream in(gcode);
    std::ostringstream out;
    std::string        line;
    while (std::getline(in, line)) {
        if (line.find("generated by") != std::string::npos || line.find("label id") != std::string::npos)
            continue;
        out << line << '\n';
    }
    return out.str();
}

// First differing line, to make a failure readable.
std::string first_difference(const std::string &a, const std::string &b)
{
    std::istringstream ia(a), ib(b);
    std::string        la, lb;
    for (size_t n = 1;; ++n) {
        const bool ga = bool(std::getline(ia, la));
        const bool gb = bool(std::getline(ib, lb));
        if (!ga && !gb)
            return "identical";
        if (!ga || !gb || la != lb)
            return "line " + std::to_string(n) + ": '" + (ga ? la : "<eof>") + "' vs '" + (gb ? lb : "<eof>") + "'";
    }
}

struct PaCheck
{
    size_t toolchanges        = 0; // tool changes followed by the new filament's nominal PA
    size_t evaluations        = 0; // "; APA Prev PA" lines checked against the printer's PA
    size_t extrusions_checked = 0; // first extrusion after each evaluation
    std::vector<std::string> errors;
};

// Replays the PA commands the way the printer sees them and checks, in G-code order, that
//  - the first PA command after every tool change is the new filament's nominal PA (BBL printers
//    wipe on the tower before writing it, so it need not come before the next extrusion),
//  - the processor's idea of the previous PA ("Prev PA") is what the printer is running,
//  - the first extrusion after each evaluation runs at the PA the processor asked for ("New PA").
PaCheck check_pa_sequence(const std::string &gcode)
{
    // "M900 K0.04 L1000 M10 ; ..." on BBL printers, "M900 K0.04; ..." otherwise.
    static const std::regex pa_cmd(R"(^M900 K([0-9.eE+-]+))");
    static const std::regex tool_cmd(R"(^T(\d+)\s*(;.*)?$)");
    static const std::regex apa(R"(^; APA Prev PA: ([0-9.eE+-]+) New PA: ([0-9.eE+-]+))");
    // M900 keeps four significant digits; the processor skips changes under EPSILON.
    const double tolerance = EPSILON + 2e-5;

    PaCheck     result;
    std::smatch m;
    bool        have_pa = false;
    double      printer_pa = 0.;
    int         pending_tool = -1;
    bool        expect_new = false;
    double      expected_pa = 0.;

    std::istringstream in(gcode);
    std::string        line;
    for (size_t n = 1; std::getline(in, line); ++n) {
        if (!line.empty() && line.back() == '\r')
            line.pop_back();
        const std::string where = "line " + std::to_string(n) + ": " + line;
        if (std::regex_search(line, m, pa_cmd)) {
            printer_pa = std::stod(m[1].str());
            have_pa    = true;
            if (pending_tool >= 0) {
                if (std::fabs(printer_pa - NOMINAL_PA[pending_tool]) > tolerance)
                    result.errors.push_back("tool change to T" + std::to_string(pending_tool) + " set the wrong PA, " + where);
                ++result.toolchanges;
                pending_tool = -1;
            }
        } else if (std::regex_match(line, m, tool_cmd)) {
            const int tool = std::stoi(m[1].str());
            if (tool < int(NOMINAL_PA.size()))
                pending_tool = tool;
        } else if (std::regex_search(line, m, apa)) {
            const double prev = std::stod(m[1].str());
            // Not the first one: the opening tool change goes through the multi-extruder branch of
            // GCode::set_extruder, which writes the nominal PA without telling the processor. The
            // first evaluation always writes its PA (new extruder), so the printer is right anyway.
            if (have_pa && result.evaluations > 0 && std::fabs(prev - printer_pa) > tolerance)
                result.errors.push_back("processor thinks PA is " + m[1].str() + " but the printer runs " +
                                        std::to_string(printer_pa) + ", " + where);
            ++result.evaluations;
            expect_new  = true;
            expected_pa = std::stod(m[2].str());
        } else if (line.rfind("G1 ", 0) == 0 && line.find(" E") != std::string::npos &&
                   (line.find(" X") != std::string::npos || line.find(" Y") != std::string::npos)) {
            if (expect_new) {
                if (std::fabs(printer_pa - expected_pa) > tolerance)
                    result.errors.push_back("extruding at PA " + std::to_string(printer_pa) + " where the processor asked for " +
                                            std::to_string(expected_pa) + ", " + where);
                ++result.extrusions_checked;
                expect_new = false;
            }
        }
    }
    return result;
}

void check_plate(bool bbl)
{
    std::string reference;
    {
        // One worker: the generator and the PA filter never overlap.
        tbb::global_control serial(tbb::global_control::max_allowed_parallelism, 1);
        reference = slice_two_filaments(bbl);
    }
    if (const char *path = std::getenv("ADAPTIVE_PA_GCODE_OUT")) {
        std::ofstream out(std::string(path) + (bbl ? ".bbl.gcode" : ".gcode"), std::ios::binary);
        out << reference;
    }

    CHECK(reference.find("PA_RESET") == std::string::npos);
    CHECK(reference.find("CP TOOLCHANGE") != std::string::npos);

    const PaCheck pa = check_pa_sequence(reference);
    INFO("tool changes " << pa.toolchanges << ", evaluations " << pa.evaluations << ", extrusions " << pa.extrusions_checked);
    for (const std::string &error : pa.errors)
        UNSCOPED_INFO(error);
    CHECK(pa.errors.empty());
    CHECK(pa.toolchanges >= 20);
    CHECK(pa.evaluations > 100);
    CHECK(pa.extrusions_checked > 100);

    const std::string expected = normalized(reference);
    for (int run = 0; run < 6; ++run) {
        const std::string gcode = slice_two_filaments(bbl);
        INFO("run " << run << ", " << first_difference(expected, normalized(gcode)));
        CHECK(normalized(gcode) == expected);
    }
}

} // namespace

TEST_CASE("Adaptive PA around tool changes does not depend on pipeline timing", "[GCode][AdaptivePA]")
{
    SECTION("generic printer") { check_plate(false); }
    SECTION("BBL printer") { check_plate(true); }
}

TEST_CASE("Adaptive PA processor is a no-op when no used tool has adaptive PA", "[GCode][AdaptivePA]")
{
    // Tool changes still emit in-band PA_RESET markers during the layer pipeline.
    // The early-out must strip those without scanning every G1, and must not emit PA_CHANGE.
    const std::string gcode = slice_two_filaments(false, false);
    REQUIRE(gcode.find("PA_CHANGE") == std::string::npos);
    REQUIRE(gcode.find("PA_RESET") == std::string::npos);
    // These tests slice a Marlin-flavoured plate, so the printer's PA command is M900.
    REQUIRE(gcode.find("M900 K") != std::string::npos);
}
