// Cost breakdown after slicing (PR 1a): the "Include filament prices in exported G-code" switch,
// time_cost invalidation and the cost of a plate whose G-code is read back (a reopened sliced 3MF).

#include <catch2/catch.hpp>

#include <fstream>
#include <iterator>
#include <sstream>
#include <string>
#include <vector>

#include <boost/filesystem.hpp>
#include <boost/nowide/cstdio.hpp>

#include "libslic3r/CostEstimate.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "test_data.hpp"

using namespace Slic3r;
using namespace Slic3r::Test;
using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;

namespace {

// Two filaments on two cubes with a prime tower, so the plate has model, flush and tower material.
DynamicPrintConfig priced_two_filaments()
{
    DynamicPrintConfig config = DynamicPrintConfig::full_print_config();
    config.set_num_extruders(2);
    config.set_num_filaments(2);
    config.option<ConfigOptionFloats>("filament_diameter")->values = { 1.75, 1.75 };
    config.option<ConfigOptionFloats>("nozzle_diameter")->values   = { 0.4, 0.4 };
    config.option<ConfigOptionStrings>("filament_colour")->values  = { "#FF0000", "#0000FF" };
    config.option<ConfigOptionFloats>("filament_density")->values  = { 1.24, 1.27 };
    config.option<ConfigOptionFloats>("filament_cost")->values     = { 25., 31.5 };
    config.option<ConfigOptionFloat>("time_cost")->value           = 1.5;
    config.option<ConfigOptionBool>("enable_prime_tower")->value   = true;
    config.option<ConfigOptionBool>("enable_support")->value       = false;
    config.option<ConfigOptionFloats>("wipe_tower_x")->values      = { 15. };
    config.option<ConfigOptionFloats>("wipe_tower_y")->values      = { 15. };
    config.option<ConfigOptionFloat>("prime_tower_width")->value   = 35.;
    config.set_deserialize_strict({ { "brim_type", "no_brim" }, { "skirt_loops", "0" }, { "wipe_tower_wall_type", "rectangle" },
                                    { "sparse_infill_density", "10%" } });
    return config;
}

void two_cubes(Model &model)
{
    ModelObject *first = model.add_object();
    first->name        = "cube-a.stl";
    first->add_volume(mesh(TestMesh::cube_20x20x20));
    first->add_instance()->set_offset(Vec3d(80., 40., 0.));
    first->ensure_on_bed();
    ModelObject *second = model.add_object();
    second->name        = "cube-b.stl";
    second->add_volume(mesh(TestMesh::cube_20x20x20));
    second->add_instance()->set_offset(Vec3d(120., 40., 0.));
    second->ensure_on_bed();
    second->volumes.front()->config.set("extruder", 2);
}

std::string read_file(const std::string &path)
{
    std::ifstream t(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(t)), std::istreambuf_iterator<char>());
}

// Slice + export into `path`, keeping the processor result.
std::string export_to(Print &print, const std::string &path, GCodeProcessorResult *result)
{
    print.set_status_silent();
    print.process();
    print.export_gcode(path, result, nullptr);
    return read_file(path);
}

std::string slice_plate(bool bbl, bool prices, GCodeProcessorResult *result = nullptr)
{
    Print print;
    Model model;
    two_cubes(model);
    print.apply(model, priced_two_filaments());
    print.is_BBL_printer() = bbl;
    print.set_gcode_filament_prices(prices);
    const boost::filesystem::path path = scratch_path();
    std::string gcode = export_to(print, path.string(), result);
    boost::nowide::remove(path.string().c_str());
    return gcode;
}

bool is_price_line(const std::string &line)
{
    return line.rfind("; filament cost =", 0) == 0 || line.rfind("; total filament cost =", 0) == 0 ||
           line.rfind("; filament_cost =", 0) == 0 || line.rfind("; time_cost =", 0) == 0;
}

// Drops what differs between two slices of the same plate in one process (header timestamp, object
// label ids, which keep counting across Models) and, when asked, the price lines.
std::string normalized(const std::string &gcode, bool drop_prices)
{
    std::istringstream in(gcode);
    std::ostringstream out;
    std::string        line;
    while (std::getline(in, line)) {
        if (line.find("generated by") != std::string::npos || line.find("label id") != std::string::npos)
            continue;
        if (drop_prices && is_price_line(line))
            continue;
        out << line << '\n';
    }
    return out.str();
}

size_t count_price_lines(const std::string &gcode)
{
    std::istringstream in(gcode);
    std::string        line;
    size_t             n = 0;
    while (std::getline(in, line))
        n += is_price_line(line);
    return n;
}

std::string first_difference(const std::string &a, const std::string &b)
{
    std::istringstream ia(a), ib(b);
    std::string        la, lb;
    for (int n = 1;; ++n) {
        const bool ga = bool(std::getline(ia, la)), gb = bool(std::getline(ib, lb));
        if (!ga && !gb)
            return "identical";
        if (!ga || !gb || la != lb)
            return "line " + std::to_string(n) + ":\n  " + (ga ? la : "<eof>") + "\n  " + (gb ? lb : "<eof>");
    }
}

} // namespace

TEST_CASE("Costs preference: off drops only the price and rate lines from the G-code", "[CostEstimate][GCode]")
{
    for (const bool bbl : { false, true }) {
        DYNAMIC_SECTION((bbl ? "Bambu Lab printer" : "other printer")) {
            const std::string with    = slice_plate(bbl, true);
            const std::string without = slice_plate(bbl, false);

            // On (today's behaviour): per-filament cost and the CONFIG_BLOCK key. The total line is
            // written only in the non-Bambu footer.
            CHECK(with.find("\n; filament cost = ") != std::string::npos);
            CHECK(with.find("\n; filament_cost = 25,31.5") != std::string::npos);
            CHECK((with.find("\n; total filament cost = ") != std::string::npos) == !bbl);
            CHECK(with.find("\n; time_cost = 1.5") != std::string::npos);
            CHECK(count_price_lines(with) == (bbl ? 3u : 4u));

            // Off: none of them (the machine rate included), everything else unchanged.
            CHECK(count_price_lines(without) == 0u);
            CHECK(without.find("filament cost") == std::string::npos);
            CHECK(without.find("filament_cost") == std::string::npos);
            CHECK(without.find("time_cost") == std::string::npos);
            CHECK(without.find("\n; filament used [g] = ") != std::string::npos);

            const std::string a = normalized(with, true), b = normalized(without, true);
            INFO(first_difference(a, b));
            CHECK(a == b);
        }
    }
}

TEST_CASE("Slice statistics cost includes machine time and matches the breakdown", "[CostEstimate][GCode]")
{
    Print                print;
    Model                model;
    GCodeProcessorResult result;
    two_cubes(model);
    print.apply(model, priced_two_filaments());
    print.set_gcode_filament_prices(false);   // the statistics must not depend on the switch
    const boost::filesystem::path path = scratch_path();
    export_to(print, path.string(), &result);
    boost::nowide::remove(path.string().c_str());

    // While slicing the processor takes the prices from the config, not from the file.
    CHECK(result.has_filament_costs);
    CHECK_THAT(result.time_cost, WithinRel(1.5, 1e-9));

    const CostBreakdown c = compute_cost(result);
    REQUIRE(c.lines.size() == 2);
    CHECK(c.prices_known);
    CHECK(c.lines[0].model_g > 0.);
    CHECK(c.lines[1].model_g > 0.);
    CHECK(c.lines[0].tower_g + c.lines[1].tower_g > 0.);
    CHECK_THAT(c.lines[0].price_per_kg, WithinRel(25., 1e-6));
    CHECK_THAT(c.lines[1].price_per_kg, WithinRel(31.5, 1e-6));
    CHECK(c.print_time_s > 0.);
    CHECK_THAT(c.machine, WithinRel(1.5 * c.print_time_s / 3600., 1e-9));
    for (const FilamentCostLine &line : c.lines) {
        // The categories account for the filament's whole extrusion.
        CHECK_THAT(line.model_g + line.support_g + line.flush_g + line.tower_g, WithinRel(line.total_g, 1e-4));
        CHECK_THAT(line.model_cost + line.support_cost + line.flush_cost + line.tower_cost, WithinRel(line.total_cost, 1e-4));
    }
    CHECK_THAT(print.print_statistics().total_cost, WithinRel(c.total, 1e-6));
    CHECK(c.total > c.material);
}

TEST_CASE("Changing time_cost re-runs only the G-code export", "[CostEstimate][Invalidation]")
{
    Print              print;
    Model              model;
    DynamicPrintConfig config = priced_two_filaments();
    two_cubes(model);
    print.apply(model, config);
    const boost::filesystem::path path = scratch_path();
    export_to(print, path.string(), nullptr);
    boost::nowide::remove(path.string().c_str());
    REQUIRE(print.is_step_done(psGCodeExport));
    REQUIRE(print.is_step_done(psWipeTower));
    REQUIRE(print.is_step_done(posSlice));
    REQUIRE(print.is_step_done(posInfill));

    config.option<ConfigOptionFloat>("time_cost")->value = 4.25;
    CHECK(print.apply(model, config) == PrintBase::APPLY_STATUS_INVALIDATED);
    CHECK_FALSE(print.is_step_done(psGCodeExport));
    CHECK(print.is_step_done(psWipeTower));
    CHECK(print.is_step_done(psSkirtBrim));
    CHECK(print.is_step_done(posSlice));
    CHECK(print.is_step_done(posPerimeters));
    CHECK(print.is_step_done(posInfill));
    CHECK(print.is_step_done(posSupportMaterial));
}

TEST_CASE("Toggling the filament prices switch re-runs only the G-code export", "[CostEstimate][Invalidation]")
{
    Print print;
    Model model;
    two_cubes(model);
    print.apply(model, priced_two_filaments());
    CHECK(print.gcode_filament_prices());   // CLI / library default: today's G-code
    // Before anything is exported there is nothing to invalidate.
    CHECK_FALSE(print.set_gcode_filament_prices(false));
    CHECK_FALSE(print.gcode_filament_prices());
    const boost::filesystem::path path = scratch_path();
    export_to(print, path.string(), nullptr);
    boost::nowide::remove(path.string().c_str());
    REQUIRE(print.is_step_done(psGCodeExport));

    CHECK_FALSE(print.set_gcode_filament_prices(false));   // unchanged
    CHECK(print.is_step_done(psGCodeExport));
    CHECK(print.set_gcode_filament_prices(true));
    CHECK_FALSE(print.is_step_done(psGCodeExport));
    CHECK(print.is_step_done(psWipeTower));
    CHECK(print.is_step_done(posSlice));
    CHECK(print.is_step_done(posInfill));
}

TEST_CASE("A plate's G-code read back (reopened sliced 3MF) keeps its cost", "[CostEstimate][3MF]")
{
    for (const bool prices : { true, false }) {
        DYNAMIC_SECTION("G-code exported with filament prices " << (prices ? "on" : "off")) {
            // The sliced 3MF stores the plate's G-code as exported; reopening it reprocesses that
            // file through Print::export_gcode_from_previous_file() with the project's config applied.
            Print                print;
            Model                model;
            GCodeProcessorResult sliced;
            two_cubes(model);
            print.apply(model, priced_two_filaments());
            print.set_gcode_filament_prices(prices);
            const boost::filesystem::path path = scratch_path();
            export_to(print, path.string(), &sliced);
            const CostBreakdown at_slice = compute_cost(sliced);

            Print reopened;
            Model reopened_model;
            two_cubes(reopened_model);
            reopened.apply(reopened_model, priced_two_filaments());
            GCodeProcessorResult reloaded;
            reopened.export_gcode_from_previous_file(path.string(), &reloaded, nullptr);
            boost::nowide::remove(path.string().c_str());

            // Prices from the G-code when it has them, else from the project's config: never the
            // processor's 29.99 placeholder, never 0.00 until the next reslice.
            CHECK(reloaded.has_filament_costs);
            REQUIRE(reloaded.filament_costs.size() >= 2);
            CHECK_THAT(double(reloaded.filament_costs[0]), WithinRel(25., 1e-6));
            CHECK_THAT(double(reloaded.filament_costs[1]), WithinRel(31.5, 1e-6));
            CHECK_THAT(reloaded.time_cost, WithinRel(1.5, 1e-9));
            const CostBreakdown at_reopen = compute_cost(reloaded);
            CHECK(at_reopen.prices_known);
            CHECK_THAT(at_reopen.material, WithinRel(at_slice.material, 1e-3));
            CHECK_THAT(at_reopen.total, WithinRel(at_slice.total, 1e-2));
            CHECK_THAT(reopened.print_statistics().total_cost, WithinRel(at_reopen.total, 1e-9));
        }
    }
}
