// libvgcode spike (tests/spike_libvgcode.md): EdgeSlicer's GCodeProcessorResult -> libvgcode input.
// CPU only: libvgcode::Viewer itself needs an OpenGL 3.2 core (or ES 3.0) context, which a test
// executable does not have, so these tests stop at libvgcode::GCodeInputData.

#include <catch2/catch.hpp>

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <chrono>
#include <set>
#include <sstream>
#include <string>

#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "slic3r/GUI/LibVGCode/EdgeVGCodeInput.hpp"
#include "libvgcode/include/PathVertex.hpp"

using namespace Slic3r;
namespace EV = Slic3r::GUI::EdgeVGCode;

namespace {

boost::filesystem::path write_temp_gcode(const std::string& name, const std::string& contents)
{
    const boost::filesystem::path dir = boost::filesystem::temp_directory_path() / "edgeslicer_tests";
    boost::filesystem::create_directories(dir);
    const boost::filesystem::path path = dir / name;
    boost::nowide::ofstream       ofs(path.string());
    ofs << contents;
    return path;
}

// Two layers in EdgeSlicer's Bambu-style tags. The second layer has an arc and two moves whose Z
// rides above the layer (what a ContourZ / ZAA surface looks like to the processor).
std::string two_layer_gcode()
{
    std::ostringstream o;
    o << "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00 UTC\n";
    o << "G28\nG90\nM83\nG92 E0\n";
    o << "; CHANGE_LAYER\n; Z_HEIGHT: 0.2\n; LAYER_HEIGHT: 0.2\nG1 Z0.2 F600\n";
    o << "G1 X10 Y10 F6000\n";
    o << "; FEATURE: Outer wall\n; LINE_WIDTH: 0.45\nG1 X60 Y10 E2 F1800\nG1 X60 Y60 E2\n";
    o << "; FEATURE: Wall over support\nG1 X10 Y60 E2\n";
    o << "; FEATURE: Bottom surface over support\nG1 X10 Y10 E2\n";
    o << "; CHANGE_LAYER\n; Z_HEIGHT: 0.4\n; LAYER_HEIGHT: 0.2\nG1 Z0.4 F600\n";
    o << "; FEATURE: Outer wall\nG2 X60 Y10 I25 J0 E3 F1800\n";
    o << "G1 X60 Y60 Z0.45 E2\nG1 X10 Y60 Z0.42 E2\nG1 X10 Y10 Z0.4 E2\n";
    o << "; CONFIG_BLOCK_START\n; filament_diameter = 1.75\n; filament_density = 1.24\n";
    for (int i = 0; i < 80; ++i)
        o << "; layer_height = 0.2\n";
    o << "; CONFIG_BLOCK_END\n";
    return o.str();
}

struct BblTagsScope
{
    bool saved = GCodeProcessor::s_IsBBLPrinter;
    BblTagsScope() { GCodeProcessor::s_IsBBLPrinter = true; }
    ~BblTagsScope() { GCodeProcessor::s_IsBBLPrinter = saved; }
};

} // namespace

TEST_CASE("libvgcode input: roles, layers, arcs and times come through from our processor", "[libvgcode][GCodeProcessor]")
{
    BblTagsScope   tags;
    const auto     path = write_temp_gcode("libvgcode_two_layers.gcode", two_layer_gcode());
    GCodeProcessor processor;
    REQUIRE_NOTHROW(processor.process_file(path.string()));
    const GCodeProcessorResult& result = processor.get_result();
    boost::filesystem::remove(path);
    REQUIRE(result.moves.size() > 5);

    EV::ConvertStats                stats;
    const libvgcode::GCodeInputData in = EV::convert(result, { "#FF8000" }, {}, &stats);
    INFO("moves=" << stats.moves << " vertices=" << stats.vertices << " phantom=" << stats.phantom_vertices
                  << " arc_vertices=" << stats.arc_vertices << " layers=" << stats.layers);
    REQUIRE(in.vertices.size() == stats.vertices);
    REQUIRE(in.tools_colors.size() == 1);

    // Both EdgeSlicer-only roles reach libvgcode as their own roles (appended to its enum).
    std::set<libvgcode::EGCodeExtrusionRole> roles;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion())
            roles.insert(v.role);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::ExternalPerimeter) == 1);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::OverSupportPerimeter) == 1);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::BottomSurfaceOverSupport) == 1);

    // Layer ids come from the layer-change tag, so the moves at Z 0.45 / 0.42 stay in layer 1 and
    // the extrusions span exactly two layers. (The legacy viewer splits layers on every Z change.)
    std::set<uint32_t> extrusion_layers;
    std::set<float>    extrusion_z;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion()) {
            extrusion_layers.insert(v.layer_id);
            extrusion_z.insert(v.position[2]);
        }
    CHECK(extrusion_layers == std::set<uint32_t>{ 0, 1 });
    CHECK(extrusion_z.size() > 2);

    // Layer ids never go down along the path (libvgcode's Layers/ViewRange assume this).
    for (size_t i = 1; i < in.vertices.size(); ++i)
        CHECK(in.vertices[i].layer_id >= in.vertices[i - 1].layer_id);

    // The G2 was expanded from the processor's interpolation points into real vertices.
    CHECK(stats.arc_vertices > 0);

    // Per-move durations add up to the processor's own estimate (normal mode).
    const float total = result.print_statistics.modes[0].time;
    double      sum   = 0.0;
    for (const libvgcode::PathVertex& v : in.vertices)
        sum += v.times[0];
    INFO("estimate=" << total << " s, sum of vertex times=" << sum << " s");
    REQUIRE(total > 0.f);
    CHECK_THAT(sum, Catch::Matchers::WithinRel(double(total), 0.01));
}

// Hidden: run with  slic3rutils_tests.exe "[libvgcode_bench]"
TEST_CASE("libvgcode input: conversion cost on a large synthetic result", "[.][libvgcode_bench]")
{
    const size_t         n = 2000000;
    GCodeProcessorResult r;
    r.moves.resize(n);
    for (size_t i = 0; i < n; ++i) {
        auto& m          = r.moves[i];
        m.type           = (i % 10 == 0) ? EMoveType::Travel : EMoveType::Extrude;
        m.extrusion_role = (i % 50 < 25) ? erPerimeter : erInternalInfill;
        m.position       = Vec3f(float(i % 200), float((i / 200) % 200), 0.2f * float(i / 40000 + 1));
        m.layer_id       = unsigned(i / 40000);
        m.width          = 0.45f;
        m.height         = 0.2f;
        m.mm3_per_mm     = 0.08f;
        m.feedrate       = 100.f;
        m.times          = { 0.01f, 0.012f };
    }
    const auto                      t0 = std::chrono::steady_clock::now();
    EV::ConvertStats                st;
    const libvgcode::GCodeInputData in = EV::convert(r, { "#FF8000" }, {}, &st);
    const auto                      t1 = std::chrono::steady_clock::now();
    const double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
    WARN("convert " << n << " moves -> " << st.vertices << " vertices in " << ms << " ms; sizeof(MoveVertex)="
                    << sizeof(GCodeProcessorResult::MoveVertex) << " sizeof(PathVertex)=" << sizeof(libvgcode::PathVertex)
                    << " CPU input MB=" << double(st.vertices * sizeof(libvgcode::PathVertex)) / 1e6
                    << " est. GPU MB (pos16+hwa16+col4+idx4 per vertex)=" << double(st.vertices * 40) / 1e6);
    CHECK(in.vertices.size() >= n - 1);
}
