// libvgcode stage 3: EdgeSlicer's GCodeProcessorResult -> libvgcode input through OrcaSlicer's
// LibVGCodeWrapper (the converter the G-code viewer uses), plus EdgeSlicer's summary-only conversion
// for the memory guard (#642). CPU only: libvgcode::Viewer::load() needs an OpenGL 3.2 core context;
// the GL side is covered by gl_core_profile_tests.cpp ("libvgcode renders ...").

#include <catch2/catch.hpp>

#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>

#include <chrono>
#include <map>
#include <set>
#include <sstream>
#include <string>

#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "slic3r/GUI/LibVGCode/LibVGCodeWrapper.hpp"
#include "libvgcode/include/PathVertex.hpp"
#include "libvgcode/include/Viewer.hpp"

using namespace Slic3r;

namespace {

boost::filesystem::path write_temp_gcode(const std::string& name, const std::string& contents)
{
    const boost::filesystem::path dir = boost::filesystem::temp_directory_path() /
        boost::filesystem::unique_path("edgeslicer_libvgcode_%%%%%%%%");
    boost::filesystem::create_directories(dir);
    const boost::filesystem::path path = dir / name;
    boost::nowide::ofstream       ofs(path.string());
    ofs << contents;
    return path;
}

// Two layers in EdgeSlicer's Bambu-style tags. The second layer has an arc and two moves whose Z
// rides above the layer (what a ContourZ / ZAA surface looks like to the processor). Pressure
// advance and acceleration are set the way Bambu / Marlin G-code does.
std::string two_layer_gcode()
{
    std::ostringstream o;
    o << "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00 UTC\n";
    o << "G28\nG90\nM83\nG92 E0\nM204 S2000\nM900 K0.04\n";
    o << "; CHANGE_LAYER\n; Z_HEIGHT: 0.2\n; LAYER_HEIGHT: 0.2\nG1 Z0.2 F600\n";
    o << "G1 X10 Y10 F6000\n";
    o << "; FEATURE: Outer wall\n; LINE_WIDTH: 0.45\nG1 X60 Y10 E2 F1800\nG1 X60 Y60 E2\n";
    o << "; FEATURE: Wall over support\nG1 X10 Y60 E2\n";
    o << "; FEATURE: Bottom surface over support\nG1 X10 Y10 E2\n";
    o << "; CHANGE_LAYER\n; Z_HEIGHT: 0.4\n; LAYER_HEIGHT: 0.2\nG1 Z0.4 F600\nM900 K0.025\n";
    o << "; FEATURE: Outer wall\nG2 X60 Y10 I25 J0 E3 F1800\n";
    o << "G1 X60 Y60 Z0.45 E2\nG1 X10 Y60 Z0.42 E2\nG1 X10 Y10 Z0.4 E2\n";
    o << "; CONFIG_BLOCK_START\n; filament_diameter = 1.75\n; filament_density = 1.24\n";
    for (int i = 0; i < 80; ++i)
        o << "; layer_height = 0.2\n";
    o << "; CONFIG_BLOCK_END\n";
    return o.str();
}

struct BblTagsScope
{
    bool saved = GCodeProcessor::s_IsBBLPrinter;
    BblTagsScope() { GCodeProcessor::s_IsBBLPrinter = true; }
    ~BblTagsScope() { GCodeProcessor::s_IsBBLPrinter = saved; }
};

void process_two_layers(GCodeProcessorResult& out)
{
    BblTagsScope   tags;
    const auto     path = write_temp_gcode("libvgcode_two_layers.gcode", two_layer_gcode());
    GCodeProcessor processor;
    processor.process_file(path.string());
    boost::filesystem::remove_all(path.parent_path());
    out = std::move(processor.extract_result());
}

std::map<uint32_t, double> layer_times(const libvgcode::GCodeInputData& in)
{
    std::map<uint32_t, double> ret;
    for (const libvgcode::PathVertex& v : in.vertices)
        ret[v.layer_id] += v.times[0];
    return ret;
}

} // namespace

TEST_CASE("libvgcode input: roles, layers, arcs, times, PA and acceleration through the wrapper", "[libvgcode][GCodeProcessor]")
{
    GCodeProcessorResult result;
    process_two_layers(result);
    REQUIRE(result.moves.size() > 5);

    libvgcode::Viewer               viewer; // the wrapper takes one; no GL needed to convert
    const libvgcode::GCodeInputData in = libvgcode::convert(result, { "#FF8000" }, {}, viewer);
    REQUIRE(in.vertices.size() >= result.moves.size() - 1);
    REQUIRE(in.tools_colors.size() == 1);
    CHECK(in.color_print_colors.size() == 1); // falls back to the tool colours

    // Both EdgeSlicer-only roles reach libvgcode as their own roles (appended to its enum), and map back.
    std::set<libvgcode::EGCodeExtrusionRole> roles;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion())
            roles.insert(v.role);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::ExternalPerimeter) == 1);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::OverSupportPerimeter) == 1);
    CHECK(roles.count(libvgcode::EGCodeExtrusionRole::BottomSurfaceOverSupport) == 1);
    CHECK(libvgcode::convert(libvgcode::convert(erOverSupportPerimeter)) == erOverSupportPerimeter);
    CHECK(libvgcode::convert(libvgcode::convert(erBottomSurfaceOverSupport)) == erBottomSurfaceOverSupport);

    // Layer ids come from the layer-change tag, so the moves at Z 0.45 / 0.42 stay in layer 1 and
    // the extrusions span exactly two layers.
    std::set<uint32_t> extrusion_layers;
    std::set<float>    extrusion_z;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion()) {
            extrusion_layers.insert(v.layer_id);
            extrusion_z.insert(v.position[2]);
        }
    CHECK(extrusion_layers == std::set<uint32_t>{ 0, 1 });
    CHECK(extrusion_z.size() > 2);

    // Layer ids never go down along the path and never skip one (libvgcode's Layers assume both).
    for (size_t i = 1; i < in.vertices.size(); ++i) {
        CHECK(in.vertices[i].layer_id >= in.vertices[i - 1].layer_id);
        CHECK(in.vertices[i].layer_id <= in.vertices[i - 1].layer_id + 1);
    }

    // The G2 arrives as several vertices sharing its G-code line (PrusaSlicer discretisation, stage 1).
    std::map<uint32_t, size_t> per_line;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion())
            ++per_line[v.gcode_id];
    size_t max_per_line = 0;
    for (const auto& [line, count] : per_line)
        max_per_line = std::max(max_per_line, count);
    CHECK(max_per_line > 4);

    // Per-move durations add up to the processor's own estimate (normal mode)...
    const float total = result.print_statistics.modes[0].time;
    double      sum   = 0.0;
    for (const libvgcode::PathVertex& v : in.vertices)
        sum += v.times[0];
    INFO("estimate=" << total << " s, sum of vertex times=" << sum << " s");
    REQUIRE(total > 0.f);
    CHECK_THAT(sum, Catch::Matchers::WithinRel(double(total), 0.01));

    // ... and libvgcode's per-layer times (what the layer slider shows now) are the processor's
    // layers_times (what it showed before, still behind slice_info's first-layer time).
    const std::map<uint32_t, double>& lt = layer_times(in);
    const std::vector<float>& table = result.print_statistics.modes[0].layers_times;
    REQUIRE(table.size() >= 2);
    for (size_t l = 0; l < table.size(); ++l) {
        INFO("layer " << l);
        const auto it = lt.find(uint32_t(l));
        const double t = it == lt.end() ? 0.0 : it->second;
        CHECK(t == Approx(double(table[l])).margin(1e-3));
    }

    // Pressure advance (#11673) and acceleration (#13169) per vertex.
    std::set<float> pa_values;
    bool            accel_seen = false;
    for (const libvgcode::PathVertex& v : in.vertices)
        if (v.is_extrusion()) {
            pa_values.insert(v.pressure_advance);
            accel_seen |= v.acceleration > 0.f;
        }
    CHECK(pa_values.count(0.04f) == 1);
    CHECK(pa_values.count(0.025f) == 1);
    CHECK(accel_seen);

    // Actual-speed points (on since stage 3): flagged on the processor side, time 0, on their segment.
    size_t speed_points = 0;
    for (const GCodeProcessorResult::MoveVertex& m : result.moves)
        if (m.actual_speed_point) {
            ++speed_points;
            CHECK(m.internal_only);
            CHECK(m.time[0] == 0.f);
            CHECK(m.actual_feedrate > 0.f);
        }
    CHECK(speed_points > 0);
}

TEST_CASE("libvgcode input: the memory guard's summary keeps layers, layer times, roles and extruders", "[libvgcode][GCodeProcessor]")
{
    GCodeProcessorResult result;
    process_two_layers(result);
    libvgcode::Viewer          viewer;
    const libvgcode::GCodeInputData full    = libvgcode::convert(result, { "#FF8000" }, {}, viewer);
    const libvgcode::GCodeInputData summary = libvgcode::convert_summary(result, { "#FF8000" }, {});

    INFO("full=" << full.vertices.size() << " summary=" << summary.vertices.size());
    CHECK(summary.vertices.size() < full.vertices.size() / 2);
    CHECK(summary.tools_colors.size() == 1);

    auto roles_of = [](const libvgcode::GCodeInputData& d) {
        std::set<libvgcode::EGCodeExtrusionRole> r;
        for (const libvgcode::PathVertex& v : d.vertices)
            if (v.is_extrusion())
                r.insert(v.role);
        return r;
    };
    CHECK(roles_of(summary) == roles_of(full));

    const std::map<uint32_t, double> full_lt = layer_times(full);
    const std::map<uint32_t, double> sum_lt  = layer_times(summary);
    REQUIRE(full_lt.size() == sum_lt.size());
    for (const auto& [layer, t] : full_lt) {
        INFO("layer " << layer);
        CHECK(sum_lt.at(layer) == Approx(t).margin(1e-4));
    }
    for (size_t i = 1; i < summary.vertices.size(); ++i)
        CHECK(summary.vertices[i].layer_id >= summary.vertices[i - 1].layer_id);
}

// Hidden: run with  slic3rutils_tests.exe "[libvgcode_bench]"
TEST_CASE("libvgcode input: conversion cost on a large synthetic result", "[.][libvgcode_bench]")
{
    const size_t         n = 2000000;
    GCodeProcessorResult r;
    r.moves.resize(n);
    for (size_t i = 0; i < n; ++i) {
        auto& m          = r.moves[i];
        m.type           = (i % 10 == 0) ? EMoveType::Travel : EMoveType::Extrude;
        m.extrusion_role = (i % 50 < 25) ? erPerimeter : erInternalInfill;
        m.position       = Vec3f(float(i % 200), float((i / 200) % 200), 0.2f * float(i / 40000 + 1));
        m.layer_id       = unsigned(i / 40000);
        m.width          = 0.45f;
        m.height         = 0.2f;
        m.mm3_per_mm     = 0.08f;
        m.feedrate       = 100.f;
        m.time           = { 0.01f, 0.012f };
    }
    libvgcode::Viewer               viewer;
    const auto                      t0 = std::chrono::steady_clock::now();
    const libvgcode::GCodeInputData in = libvgcode::convert(r, { "#FF8000" }, {}, viewer);
    const auto                      t1 = std::chrono::steady_clock::now();
    const libvgcode::GCodeInputData su = libvgcode::convert_summary(r, { "#FF8000" }, {});
    const auto                      t2 = std::chrono::steady_clock::now();
    using ms_t = std::chrono::duration<double, std::milli>;
    const double convert_ms = ms_t(t1 - t0).count();
    const double summary_ms = ms_t(t2 - t1).count();
    WARN("convert " << n << " moves -> " << in.vertices.size() << " vertices in " << convert_ms << " ms; summary -> "
                    << su.vertices.size() << " vertices in " << summary_ms << " ms; sizeof(MoveVertex)="
                    << sizeof(GCodeProcessorResult::MoveVertex) << " sizeof(PathVertex)=" << sizeof(libvgcode::PathVertex));
    CHECK(in.vertices.size() >= n - 1);
}
