// GENERATED FILE - do not edit by hand.
// Source: Bambu Studio 02.08.02.61 (commit 66e4054776), src/libslic3r/PrintConfig.cpp
// Generator: scripts/gen_bambu_known_keys.py (see docs/bambu-3mf-export.md)
#include "BambuExport.hpp"

namespace Slic3r {
namespace BambuExport {

const char *bambu_reference_version() { return "02.08.02.61"; }
const char *bambu_reference_commit() { return "66e4054776"; }

// Every option Bambu Studio keeps when it loads a project: key, Bambu type, nullable,
// per-extruder variant class, accepted enum values joined by "|" (enum options only).
// Keys Bambu declares but discards in its own handle_legacy() are not listed:
//   acceleration adaptive_layer_height apply_top_surface_compensation bed_size bed_temperature bed_temperature_difference bed_temperature_initial_layer can_add_auxiliary_fan can_switch_nozzle_type chamber_temperature duplicate duplicate_grid extra_flush_volume g0 long_retraction_when_cut max_print_speed max_volumetric_extrusion_rate_slope_negative max_volumetric_extrusion_rate_slope_positive max_volumetric_speed nozzle_hrc only_one_wall_top prime_volume print_center reduce_infill_retraction remove_bed_leveling remove_extrusion_calibration remove_freq_sweep retraction_distance_when_cut rotate scale spaghetti_detector support_closing_radius support_remove_small_overhangs support_sharp_tails support_transition_line_width support_transition_speed support_with_sheath tree_support_brim_width tree_support_collision_resolution tree_support_with_infill wipe_tower_per_color_wipe z_hop_type
const std::vector<BambuKeyDef> &bambu_key_defs()
{
    static const std::vector<BambuKeyDef> defs = {
        { "accel_to_decel_enable", "coBool", false, VariantClass::None, nullptr },
        { "accel_to_decel_factor", "coPercent", false, VariantClass::None, nullptr },
        { "activate_air_filtration", "coBools", false, VariantClass::None, nullptr },
        { "additional_cooling_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "additional_fan_full_speed_layer", "coInts", false, VariantClass::None, nullptr },
        { "alternate_extra_wall", "coBool", false, VariantClass::None, nullptr },
        { "ams_filament_load_time_ams", "coFloat", false, VariantClass::None, nullptr },
        { "ams_filament_load_time_ams_lite", "coFloat", false, VariantClass::None, nullptr },
        { "ams_filament_load_time_n3f_s", "coFloat", false, VariantClass::None, nullptr },
        { "ams_filament_unload_time_ams", "coFloat", false, VariantClass::None, nullptr },
        { "ams_filament_unload_time_ams_lite", "coFloat", false, VariantClass::None, nullptr },
        { "ams_filament_unload_time_n3f_s", "coFloat", false, VariantClass::None, nullptr },
        { "apply_scarf_seam_on_circles", "coBool", false, VariantClass::None, nullptr },
        { "auxiliary_fan", "coBool", false, VariantClass::None, nullptr },
        { "avoid_crossing_wall_includes_support", "coBool", false, VariantClass::None, nullptr },
        { "bed_custom_model", "coString", false, VariantClass::None, nullptr },
        { "bed_custom_texture", "coString", false, VariantClass::None, nullptr },
        { "bed_exclude_area", "coPoints", false, VariantClass::None, nullptr },
        { "bed_heat_soak_area", "coPoints", false, VariantClass::None, nullptr },
        { "bed_temperature_formula", "coEnum", false, VariantClass::None, "by_first_filament|by_highest_temp" },
        { "before_layer_change_gcode", "coString", false, VariantClass::None, nullptr },
        { "best_object_pos", "coPoint", false, VariantClass::None, nullptr },
        { "bottom_color_penetration_layers", "coInt", false, VariantClass::None, nullptr },
        { "bottom_shell_layers", "coInt", false, VariantClass::None, nullptr },
        { "bottom_shell_thickness", "coFloat", false, VariantClass::None, nullptr },
        { "bottom_surface_density", "coPercent", false, VariantClass::None, nullptr },
        { "bottom_surface_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "bridge_angle", "coFloat", false, VariantClass::None, nullptr },
        { "bridge_flow", "coFloat", false, VariantClass::None, nullptr },
        { "bridge_no_support", "coBool", false, VariantClass::None, nullptr },
        { "bridge_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "brim_object_gap", "coFloat", false, VariantClass::None, nullptr },
        { "brim_type", "coEnum", false, VariantClass::None, "no_brim|outer_only|inner_only|outer_and_inner|auto_brim|brim_ears" },
        { "brim_width", "coFloat", false, VariantClass::None, nullptr },
        { "chamber_temperatures", "coInts", false, VariantClass::None, nullptr },
        { "change_filament_gcode", "coString", false, VariantClass::None, nullptr },
        { "circle_compensation_manual_offset", "coFloat", false, VariantClass::None, nullptr },
        { "circle_compensation_speed", "coFloats", false, VariantClass::None, nullptr },
        { "close_additional_fan_first_x_layers", "coInts", false, VariantClass::None, nullptr },
        { "close_fan_the_first_x_layers", "coInts", false, VariantClass::None, nullptr },
        { "compatible_machine_expression_group", "coStrings", false, VariantClass::None, nullptr },
        { "compatible_printers", "coStrings", false, VariantClass::None, nullptr },
        { "compatible_printers_condition", "coString", false, VariantClass::None, nullptr },
        { "compatible_prints", "coStrings", false, VariantClass::None, nullptr },
        { "compatible_prints_condition", "coString", false, VariantClass::None, nullptr },
        { "compatible_process_expression_group", "coStrings", false, VariantClass::None, nullptr },
        { "complete_print_exhaust_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "cool_plate_temp", "coInts", false, VariantClass::None, nullptr },
        { "cool_plate_temp_initial_layer", "coInts", false, VariantClass::None, nullptr },
        { "cooling_filter_enabled", "coBool", false, VariantClass::None, nullptr },
        { "cooling_perimeter_transition_distance", "coFloats", false, VariantClass::None, nullptr },
        { "cooling_slowdown_logic", "coEnums", false, VariantClass::None, "uniform_cooling|consistent_surface" },
        { "counter_coef_1", "coFloats", false, VariantClass::None, nullptr },
        { "counter_coef_2", "coFloats", false, VariantClass::None, nullptr },
        { "counter_coef_3", "coFloats", false, VariantClass::None, nullptr },
        { "counter_limit_max", "coFloats", false, VariantClass::None, nullptr },
        { "counter_limit_min", "coFloats", false, VariantClass::None, nullptr },
        { "counterbore_hole_bridging", "coEnum", false, VariantClass::None, "none|partiallybridge|sacrificiallayer" },
        { "curr_bed_type", "coEnum", false, VariantClass::None, "Default Plate|Cool Plate|Engineering Plate|High Temp Plate|Textured PEI Plate|Supertack Plate" },
        { "default_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "default_ams_type", "coInt", false, VariantClass::None, nullptr },
        { "default_filament_colour", "coStrings", false, VariantClass::None, nullptr },
        { "default_filament_profile", "coStrings", false, VariantClass::None, nullptr },
        { "default_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "default_nozzle_volume_type", "coEnums", false, VariantClass::Extruder, "Standard|High Flow|TPU High Flow|Hybrid|E3D High Flow" },
        { "default_print_profile", "coString", false, VariantClass::None, nullptr },
        { "deretraction_speed", "coFloats", true, VariantClass::Printer, nullptr },
        { "detect_floating_vertical_shell", "coBool", false, VariantClass::None, nullptr },
        { "detect_narrow_internal_solid_infill", "coBool", false, VariantClass::None, nullptr },
        { "detect_overhang_wall", "coBool", false, VariantClass::None, nullptr },
        { "detect_thin_wall", "coBool", false, VariantClass::None, nullptr },
        { "diameter_limit", "coFloats", false, VariantClass::None, nullptr },
        { "different_settings_to_system", "coStrings", false, VariantClass::None, nullptr },
        { "draft_shield", "coEnum", false, VariantClass::None, "disabled|limited|enabled" },
        { "during_print_exhaust_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "elefant_foot_compensation", "coFloat", false, VariantClass::None, nullptr },
        { "embedding_wall_into_infill", "coBool", false, VariantClass::None, nullptr },
        { "enable_arc_fitting", "coBool", false, VariantClass::None, nullptr },
        { "enable_circle_compensation", "coBool", false, VariantClass::None, nullptr },
        { "enable_filament_dynamic_map", "coBool", false, VariantClass::None, nullptr },
        { "enable_height_slowdown", "coBools", true, VariantClass::Print, nullptr },
        { "enable_long_retraction_when_cut", "coInt", false, VariantClass::None, nullptr },
        { "enable_mixed_color_sublayer", "coBool", false, VariantClass::None, nullptr },
        { "enable_order_independent_overlap_carving", "coBool", false, VariantClass::None, nullptr },
        { "enable_overhang_bridge_fan", "coBools", false, VariantClass::None, nullptr },
        { "enable_overhang_speed", "coBools", true, VariantClass::Print, nullptr },
        { "enable_pre_heating", "coBool", false, VariantClass::None, nullptr },
        { "enable_pressure_advance", "coBools", false, VariantClass::None, nullptr },
        { "enable_prime_tower", "coBool", false, VariantClass::None, nullptr },
        { "enable_support", "coBool", false, VariantClass::None, nullptr },
        { "enable_support_ironing", "coBool", false, VariantClass::None, nullptr },
        { "enable_tower_interface_features", "coBool", false, VariantClass::None, nullptr },
        { "enable_wrapping_detection", "coBool", false, VariantClass::None, nullptr },
        { "enforce_support_layers", "coInt", false, VariantClass::None, nullptr },
        { "eng_plate_temp", "coInts", false, VariantClass::None, nullptr },
        { "eng_plate_temp_initial_layer", "coInts", false, VariantClass::None, nullptr },
        { "ensure_vertical_shell_thickness", "coEnum", false, VariantClass::None, "disabled|partial|enabled" },
        { "exclude_object", "coBool", false, VariantClass::None, nullptr },
        { "extruder", "coInt", false, VariantClass::None, nullptr },
        { "extruder_ams_count", "coStrings", false, VariantClass::None, nullptr },
        { "extruder_clearance_dist_to_rod", "coFloat", false, VariantClass::None, nullptr },
        { "extruder_clearance_height_to_lid", "coFloat", false, VariantClass::None, nullptr },
        { "extruder_clearance_height_to_rod", "coFloat", false, VariantClass::None, nullptr },
        { "extruder_clearance_max_radius", "coFloat", false, VariantClass::None, nullptr },
        { "extruder_colour", "coStrings", false, VariantClass::None, nullptr },
        { "extruder_max_nozzle_count", "coInts", true, VariantClass::Extruder, nullptr },
        { "extruder_nozzle_count", "coInts", false, VariantClass::None, nullptr },
        { "extruder_nozzle_stats", "coStrings", false, VariantClass::None, nullptr },
        { "extruder_nozzle_stats_new", "coStrings", false, VariantClass::None, nullptr },
        { "extruder_nozzle_volume_type", "coEnums", false, VariantClass::None, "Standard|High Flow|TPU High Flow|Hybrid|E3D High Flow" },
        { "extruder_offset", "coPoints", false, VariantClass::None, nullptr },
        { "extruder_printable_area", "coPointsGroups", false, VariantClass::Extruder, nullptr },
        { "extruder_printable_height", "coFloats", true, VariantClass::Extruder, nullptr },
        { "extruder_type", "coEnums", false, VariantClass::Extruder, "Direct Drive|Bowden" },
        { "extruder_variant_list", "coStrings", false, VariantClass::None, nullptr },
        { "fan_cooling_layer_time", "coInts", false, VariantClass::None, nullptr },
        { "fan_direction", "coEnum", false, VariantClass::None, "undefine|left|right|both" },
        { "fan_max_speed", "coInts", false, VariantClass::None, nullptr },
        { "fan_min_speed", "coInts", false, VariantClass::None, nullptr },
        { "farthest_point_timelapse", "coBool", false, VariantClass::None, nullptr },
        { "filament_adaptive_volumetric_speed", "coBools", true, VariantClass::Filament, nullptr },
        { "filament_adhesiveness_category", "coInts", false, VariantClass::None, nullptr },
        { "filament_bridge_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_change_length", "coFloats", false, VariantClass::None, nullptr },
        { "filament_change_length_nc", "coFloats", false, VariantClass::None, nullptr },
        { "filament_colour", "coStrings", false, VariantClass::None, nullptr },
        { "filament_colour_type", "coStrings", false, VariantClass::None, nullptr },
        { "filament_cooling_before_tower", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_cost", "coFloats", false, VariantClass::None, nullptr },
        { "filament_density", "coFloats", false, VariantClass::None, nullptr },
        { "filament_deretraction_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_dev_ams_drying_ams_limitations", "coStrings", false, VariantClass::None, nullptr },
        { "filament_dev_ams_drying_heat_distortion_temperature", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_ams_drying_temperature", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_ams_drying_time", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_chamber_drying_bed_temperature", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_chamber_drying_time", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_drying_cooling_temperature", "coFloats", false, VariantClass::None, nullptr },
        { "filament_dev_drying_softening_temperature", "coFloats", false, VariantClass::None, nullptr },
        { "filament_diameter", "coFloats", false, VariantClass::None, nullptr },
        { "filament_enable_overhang_speed", "coBools", true, VariantClass::Filament, nullptr },
        { "filament_end_gcode", "coStrings", false, VariantClass::None, nullptr },
        { "filament_extruder_compatibility", "coInts", false, VariantClass::None, nullptr },
        { "filament_extruder_id", "coInts", false, VariantClass::None, nullptr },
        { "filament_extruder_variant", "coStrings", false, VariantClass::Filament, nullptr },
        { "filament_flow_ratio", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_flush_temp", "coInts", true, VariantClass::Filament, nullptr },
        { "filament_flush_temp_fast", "coInts", true, VariantClass::Filament, nullptr },
        { "filament_flush_volumetric_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_ids", "coStrings", false, VariantClass::None, nullptr },
        { "filament_is_mixed", "coBools", false, VariantClass::None, nullptr },
        { "filament_is_support", "coBools", false, VariantClass::None, nullptr },
        { "filament_long_retractions_when_cut", "coBools", true, VariantClass::Filament, nullptr },
        { "filament_map", "coInts", false, VariantClass::None, nullptr },
        { "filament_map_2", "coInts", false, VariantClass::None, nullptr },
        { "filament_map_mode", "coEnum", false, VariantClass::None, "Auto For Flush|Auto For Match|Manual|Nozzle Manual|Auto For Quality" },
        { "filament_max_volumetric_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_metal_stickiness", "coEnums", false, VariantClass::None, "None|Low|Medium|High" },
        { "filament_minimal_purge_on_wipe_tower", "coFloats", false, VariantClass::None, nullptr },
        { "filament_mixed_components", "coStrings", false, VariantClass::None, nullptr },
        { "filament_mixed_gradient", "coBools", false, VariantClass::None, nullptr },
        { "filament_mixed_gradient_curve", "coStrings", false, VariantClass::None, nullptr },
        { "filament_mixed_gradient_per_part", "coBools", false, VariantClass::None, nullptr },
        { "filament_mixed_gradient_range", "coStrings", false, VariantClass::None, nullptr },
        { "filament_mixed_sublayer_ratios", "coStrings", false, VariantClass::None, nullptr },
        { "filament_multi_colour", "coStrings", false, VariantClass::None, nullptr },
        { "filament_notes", "coString", false, VariantClass::None, nullptr },
        { "filament_nozzle_map", "coInts", false, VariantClass::None, nullptr },
        { "filament_overhang_1_4_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_overhang_2_4_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_overhang_3_4_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_overhang_4_4_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_overhang_totally_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_pre_cooling_temperature", "coInts", true, VariantClass::Filament, nullptr },
        { "filament_pre_cooling_temperature_nc", "coInts", true, VariantClass::Filament, nullptr },
        { "filament_preheat_temperature_delta", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_prime_volume", "coFloats", false, VariantClass::None, nullptr },
        { "filament_prime_volume_nc", "coFloats", false, VariantClass::None, nullptr },
        { "filament_printable", "coInts", false, VariantClass::None, nullptr },
        { "filament_ramming_travel_time", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_ramming_travel_time_nc", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_ramming_volumetric_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_ramming_volumetric_speed_nc", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retract_before_wipe", "coPercents", true, VariantClass::Filament, nullptr },
        { "filament_retract_length_nc", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retract_lift_above", "coFloats", true, VariantClass::None, nullptr },
        { "filament_retract_lift_below", "coFloats", true, VariantClass::None, nullptr },
        { "filament_retract_restart_extra", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retract_when_changing_layer", "coBools", true, VariantClass::Filament, nullptr },
        { "filament_retraction_distances_when_cut", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retraction_length", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retraction_minimum_travel", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_retraction_speed", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_scarf_gap", "coFloatsOrPercents", false, VariantClass::None, nullptr },
        { "filament_scarf_height", "coFloatsOrPercents", false, VariantClass::None, nullptr },
        { "filament_scarf_length", "coFloats", false, VariantClass::None, nullptr },
        { "filament_scarf_seam_type", "coEnums", false, VariantClass::None, "none|external|all" },
        { "filament_self_index", "coInts", false, VariantClass::None, nullptr },
        { "filament_settings_id", "coStrings", false, VariantClass::None, nullptr },
        { "filament_shrink", "coPercents", false, VariantClass::None, nullptr },
        { "filament_soluble", "coBools", false, VariantClass::None, nullptr },
        { "filament_start_gcode", "coStrings", false, VariantClass::None, nullptr },
        { "filament_tower_interface_pre_extrusion_dist", "coFloats", false, VariantClass::None, nullptr },
        { "filament_tower_interface_pre_extrusion_length", "coFloats", false, VariantClass::None, nullptr },
        { "filament_tower_interface_print_temp", "coInts", false, VariantClass::None, nullptr },
        { "filament_tower_interface_purge_volume", "coFloats", false, VariantClass::None, nullptr },
        { "filament_tower_ironing_area", "coFloats", false, VariantClass::None, nullptr },
        { "filament_type", "coStrings", false, VariantClass::None, nullptr },
        { "filament_velocity_adaptation_factor", "coFloats", false, VariantClass::None, nullptr },
        { "filament_vendor", "coStrings", false, VariantClass::None, nullptr },
        { "filament_volume_map", "coInts", false, VariantClass::None, nullptr },
        { "filament_wipe", "coBools", true, VariantClass::Filament, nullptr },
        { "filament_wipe_distance", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_z_hop", "coFloats", true, VariantClass::Filament, nullptr },
        { "filament_z_hop_types", "coEnums", true, VariantClass::Filament, "Auto Lift|Normal Lift|Slope Lift|Spiral Lift" },
        { "filename_format", "coString", false, VariantClass::None, nullptr },
        { "fill_multiline", "coInt", false, VariantClass::None, nullptr },
        { "filter_out_gap_fill", "coFloat", false, VariantClass::None, nullptr },
        { "first_layer_print_sequence", "coInts", false, VariantClass::None, nullptr },
        { "first_layer_sequence_choice", "coEnum", false, VariantClass::None, "Auto|Customize" },
        { "first_x_layer_fan_speed", "coFloats", false, VariantClass::None, nullptr },
        { "first_x_layer_part_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "flush_into_infill", "coBool", false, VariantClass::None, nullptr },
        { "flush_into_objects", "coBool", false, VariantClass::None, nullptr },
        { "flush_into_support", "coBool", false, VariantClass::None, nullptr },
        { "flush_multiplier", "coFloats", false, VariantClass::None, nullptr },
        { "flush_multiplier_fast", "coFloats", false, VariantClass::None, nullptr },
        { "flush_volumes_matrix", "coFloats", false, VariantClass::None, nullptr },
        { "flush_volumes_vector", "coFloats", false, VariantClass::None, nullptr },
        { "full_fan_speed_layer", "coInts", false, VariantClass::None, nullptr },
        { "fuzzy_skin", "coEnum", false, VariantClass::None, "none|external|all|allwalls|disabled_fuzzy" },
        { "fuzzy_skin_first_layer", "coBool", false, VariantClass::None, nullptr },
        { "fuzzy_skin_mode", "coEnum", false, VariantClass::None, "displacement|extrusion|combined" },
        { "fuzzy_skin_noise_type", "coEnum", false, VariantClass::None, "classic|perlin|billow|ridgedmulti|voronoi" },
        { "fuzzy_skin_octaves", "coInt", false, VariantClass::None, nullptr },
        { "fuzzy_skin_persistence", "coFloat", false, VariantClass::None, nullptr },
        { "fuzzy_skin_point_distance", "coFloat", false, VariantClass::None, nullptr },
        { "fuzzy_skin_scale", "coFloat", false, VariantClass::None, nullptr },
        { "fuzzy_skin_thickness", "coFloat", false, VariantClass::None, nullptr },
        { "gap_infill_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "gcode_add_line_number", "coBool", false, VariantClass::None, nullptr },
        { "gcode_flavor", "coEnum", false, VariantClass::None, "marlin|klipper|reprap|reprapfirmware|repetier|teacup|makerware|marlin2|sailfish|smoothie|mach3|machinekit|no-extrusion" },
        { "grab_length", "coFloats", false, VariantClass::None, nullptr },
        { "group_algo_with_time", "coBool", false, VariantClass::None, nullptr },
        { "has_filament_switcher", "coBool", false, VariantClass::None, nullptr },
        { "has_scarf_joint_seam", "coBool", false, VariantClass::None, nullptr },
        { "head_wrap_detect_zone", "coPoints", false, VariantClass::None, nullptr },
        { "hole_coef_1", "coFloats", false, VariantClass::None, nullptr },
        { "hole_coef_2", "coFloats", false, VariantClass::None, nullptr },
        { "hole_coef_3", "coFloats", false, VariantClass::None, nullptr },
        { "hole_limit_max", "coFloats", false, VariantClass::None, nullptr },
        { "hole_limit_min", "coFloats", false, VariantClass::None, nullptr },
        { "host_type", "coEnum", false, VariantClass::None, "prusalink|octoprint|duet|flashair|astrobox|repetier|mks" },
        { "hot_plate_temp", "coInts", false, VariantClass::None, nullptr },
        { "hot_plate_temp_initial_layer", "coInts", false, VariantClass::None, nullptr },
        { "hotend_cooling_rate", "coFloats", true, VariantClass::Printer, nullptr },
        { "hotend_heating_rate", "coFloats", true, VariantClass::Printer, nullptr },
        { "impact_strength_z", "coFloats", false, VariantClass::None, nullptr },
        { "independent_support_layer_height", "coBool", false, VariantClass::None, nullptr },
        { "infill_combination", "coBool", false, VariantClass::None, nullptr },
        { "infill_direction", "coFloat", false, VariantClass::None, nullptr },
        { "infill_instead_top_bottom_surfaces", "coBool", false, VariantClass::None, nullptr },
        { "infill_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "infill_lock_depth", "coFloat", false, VariantClass::None, nullptr },
        { "infill_rotate_step", "coFloat", false, VariantClass::None, nullptr },
        { "infill_shift_step", "coFloat", false, VariantClass::None, nullptr },
        { "infill_wall_overlap", "coPercent", false, VariantClass::None, nullptr },
        { "inherits", "coString", false, VariantClass::None, nullptr },
        { "inherits_group", "coStrings", false, VariantClass::None, nullptr },
        { "initial_layer_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "initial_layer_flow_ratio", "coFloat", false, VariantClass::None, nullptr },
        { "initial_layer_infill_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "initial_layer_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "initial_layer_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "initial_layer_print_height", "coFloat", false, VariantClass::None, nullptr },
        { "initial_layer_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "initial_layer_travel_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "inner_wall_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "inner_wall_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "inner_wall_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "inner_wall_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "interface_shells", "coBool", false, VariantClass::None, nullptr },
        { "interlocking_beam", "coBool", false, VariantClass::None, nullptr },
        { "interlocking_beam_layer_count", "coInt", false, VariantClass::None, nullptr },
        { "interlocking_beam_width", "coFloat", false, VariantClass::None, nullptr },
        { "interlocking_boundary_avoidance", "coInt", false, VariantClass::None, nullptr },
        { "interlocking_depth", "coInt", false, VariantClass::None, nullptr },
        { "interlocking_orientation", "coFloat", false, VariantClass::None, nullptr },
        { "internal_bridge_support_thickness", "coFloat", false, VariantClass::None, nullptr },
        { "internal_solid_infill_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "internal_solid_infill_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "internal_solid_infill_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "ironing_direction", "coFloat", false, VariantClass::None, nullptr },
        { "ironing_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "ironing_flow", "coPercent", false, VariantClass::None, nullptr },
        { "ironing_inset", "coFloat", false, VariantClass::None, nullptr },
        { "ironing_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "ironing_spacing", "coFloat", false, VariantClass::None, nullptr },
        { "ironing_speed", "coFloat", false, VariantClass::None, nullptr },
        { "ironing_type", "coEnum", false, VariantClass::None, "no ironing|top|topmost|solid" },
        { "is_infill_first", "coBool", false, VariantClass::None, nullptr },
        { "layer_change_gcode", "coString", false, VariantClass::None, nullptr },
        { "layer_height", "coFloat", false, VariantClass::None, nullptr },
        { "line_width", "coFloat", false, VariantClass::None, nullptr },
        { "locked_skeleton_infill_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "locked_skin_infill_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "long_retractions_when_cut", "coBools", true, VariantClass::Printer, nullptr },
        { "long_retractions_when_ec", "coBools", true, VariantClass::Filament, nullptr },
        { "machine_bed_mass_Y", "coFloat", false, VariantClass::None, nullptr },
        { "machine_end_gcode", "coString", false, VariantClass::None, nullptr },
        { "machine_hotend_change_time", "coFloat", false, VariantClass::None, nullptr },
        { "machine_load_filament_time", "coFloat", false, VariantClass::None, nullptr },
        { "machine_max_acceleration_e", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_extruding", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_retracting", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_travel", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_x", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_y", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_acceleration_z", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_force_Y", "coFloat", false, VariantClass::None, nullptr },
        { "machine_max_jerk_e", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_jerk_x", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_jerk_y", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_jerk_z", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_printed_mass", "coFloat", false, VariantClass::None, nullptr },
        { "machine_max_speed_e", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_speed_x", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_speed_y", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_max_speed_z", "coFloats", true, VariantClass::PrinterPair, nullptr },
        { "machine_min_extruding_rate", "coFloats", false, VariantClass::None, nullptr },
        { "machine_min_travel_rate", "coFloats", false, VariantClass::None, nullptr },
        { "machine_pause_gcode", "coString", false, VariantClass::None, nullptr },
        { "machine_prepare_compensation_time", "coFloat", false, VariantClass::None, nullptr },
        { "machine_start_gcode", "coString", false, VariantClass::None, nullptr },
        { "machine_switch_extruder_time", "coFloat", false, VariantClass::None, nullptr },
        { "machine_unload_filament_time", "coFloat", false, VariantClass::None, nullptr },
        { "master_extruder_id", "coInt", false, VariantClass::None, nullptr },
        { "max_bridge_length", "coFloat", false, VariantClass::None, nullptr },
        { "max_layer_height", "coFloats", true, VariantClass::Extruder, nullptr },
        { "max_travel_detour_distance", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "min_bead_width", "coPercent", false, VariantClass::None, nullptr },
        { "min_feature_size", "coPercent", false, VariantClass::None, nullptr },
        { "min_layer_height", "coFloats", true, VariantClass::Extruder, nullptr },
        { "minimum_sparse_infill_area", "coFloat", false, VariantClass::None, nullptr },
        { "mmu_segmented_region_interlocking_depth", "coFloat", false, VariantClass::None, nullptr },
        { "mmu_segmented_region_max_width", "coFloat", false, VariantClass::None, nullptr },
        { "monotonic_travel_into_wall", "coPercent", false, VariantClass::None, nullptr },
        { "no_slow_down_for_cooling_on_outwalls", "coBools", false, VariantClass::None, nullptr },
        { "nozzle_diameter", "coFloats", true, VariantClass::Extruder, nullptr },
        { "nozzle_flush_dataset", "coInts", true, VariantClass::Printer, nullptr },
        { "nozzle_height", "coFloat", false, VariantClass::None, nullptr },
        { "nozzle_temperature", "coInts", true, VariantClass::Filament, nullptr },
        { "nozzle_temperature_initial_layer", "coInts", true, VariantClass::Filament, nullptr },
        { "nozzle_temperature_range_high", "coInts", false, VariantClass::None, nullptr },
        { "nozzle_temperature_range_low", "coInts", false, VariantClass::None, nullptr },
        { "nozzle_type", "coEnums", true, VariantClass::Printer, "undefine|hardened_steel|stainless_steel|tungsten_carbide|brass" },
        { "nozzle_volume", "coFloats", true, VariantClass::Printer, nullptr },
        { "nozzle_volume_type", "coEnums", false, VariantClass::None, "Standard|High Flow|TPU High Flow|Hybrid|E3D High Flow" },
        { "only_one_wall_first_layer", "coBool", false, VariantClass::None, nullptr },
        { "ooze_prevention", "coBool", false, VariantClass::None, nullptr },
        { "other_layers_print_sequence", "coInts", false, VariantClass::None, nullptr },
        { "other_layers_print_sequence_nums", "coInt", false, VariantClass::None, nullptr },
        { "other_layers_sequence_choice", "coEnum", false, VariantClass::None, "Auto|Customize" },
        { "outer_wall_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "outer_wall_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "outer_wall_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "outer_wall_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "overhang_1_4_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "overhang_2_4_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "overhang_3_4_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "overhang_4_4_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "overhang_fan_speed", "coInts", false, VariantClass::None, nullptr },
        { "overhang_fan_threshold", "coEnums", false, VariantClass::None, "0%|10%|25%|50%|75%|95%" },
        { "overhang_threshold_participating_cooling", "coEnums", false, VariantClass::None, "0%|10%|25%|50%|75%|95%" },
        { "overhang_totally_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "override_filament_scarf_seam_setting", "coBool", false, VariantClass::None, nullptr },
        { "override_process_overhang_speed", "coBools", true, VariantClass::Filament, nullptr },
        { "physical_extruder_map", "coInts", false, VariantClass::None, nullptr },
        { "post_process", "coStrings", false, VariantClass::None, nullptr },
        { "pre_start_fan_time", "coFloats", false, VariantClass::None, nullptr },
        { "precise_outer_wall", "coBool", false, VariantClass::None, nullptr },
        { "precise_z_height", "coBool", false, VariantClass::None, nullptr },
        { "preset_name", "coString", false, VariantClass::None, nullptr },
        { "preset_names", "coStrings", false, VariantClass::None, nullptr },
        { "pressure_advance", "coFloats", false, VariantClass::None, nullptr },
        { "prime_tower_brim_width", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_enable_framework", "coBool", false, VariantClass::None, nullptr },
        { "prime_tower_extra_rib_length", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_fillet_wall", "coBool", false, VariantClass::None, nullptr },
        { "prime_tower_flat_ironing", "coBool", false, VariantClass::None, nullptr },
        { "prime_tower_infill_gap", "coPercent", false, VariantClass::None, nullptr },
        { "prime_tower_lift_height", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_lift_speed", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_max_speed", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_rib_wall", "coBool", false, VariantClass::None, nullptr },
        { "prime_tower_rib_width", "coFloat", false, VariantClass::None, nullptr },
        { "prime_tower_skip_points", "coBool", false, VariantClass::None, nullptr },
        { "prime_tower_width", "coFloat", false, VariantClass::None, nullptr },
        { "prime_volume_mode", "coEnum", false, VariantClass::None, "Default|Saving|Fast" },
        { "print_compatible_printers", "coStrings", false, VariantClass::None, nullptr },
        { "print_extruder_id", "coInts", false, VariantClass::Print, nullptr },
        { "print_extruder_variant", "coStrings", false, VariantClass::Print, nullptr },
        { "print_flow_ratio", "coFloat", false, VariantClass::None, nullptr },
        { "print_host", "coString", false, VariantClass::None, nullptr },
        { "print_host_webui", "coString", false, VariantClass::None, nullptr },
        { "print_in_clockwise", "coBool", false, VariantClass::None, nullptr },
        { "print_sequence", "coEnum", false, VariantClass::None, "by layer|by object" },
        { "print_settings_id", "coString", false, VariantClass::None, nullptr },
        { "printable_area", "coPoints", false, VariantClass::None, nullptr },
        { "printable_height", "coFloat", false, VariantClass::None, nullptr },
        { "printer_extruder_id", "coInts", false, VariantClass::Printer, nullptr },
        { "printer_extruder_variant", "coStrings", false, VariantClass::Printer, nullptr },
        { "printer_model", "coString", false, VariantClass::None, nullptr },
        { "printer_notes", "coString", false, VariantClass::None, nullptr },
        { "printer_settings_id", "coString", false, VariantClass::None, nullptr },
        { "printer_structure", "coEnum", false, VariantClass::None, "undefine|corexy|i3|hbot|delta" },
        { "printer_technology", "coEnum", false, VariantClass::None, "FFF|SLA" },
        { "printer_variant", "coString", false, VariantClass::None, nullptr },
        { "printhost_apikey", "coString", false, VariantClass::None, nullptr },
        { "printhost_authorization_type", "coEnum", false, VariantClass::None, "key|user" },
        { "printhost_cafile", "coString", false, VariantClass::None, nullptr },
        { "printhost_password", "coString", false, VariantClass::None, nullptr },
        { "printhost_port", "coString", false, VariantClass::None, nullptr },
        { "printhost_ssl_ignore_revoke", "coBool", false, VariantClass::None, nullptr },
        { "printhost_user", "coString", false, VariantClass::None, nullptr },
        { "printing_by_object_gcode", "coString", false, VariantClass::None, nullptr },
        { "process_notes", "coString", false, VariantClass::None, nullptr },
        { "raft_contact_distance", "coFloat", false, VariantClass::None, nullptr },
        { "raft_expansion", "coFloat", false, VariantClass::None, nullptr },
        { "raft_first_layer_density", "coPercent", false, VariantClass::None, nullptr },
        { "raft_first_layer_expansion", "coFloat", false, VariantClass::None, nullptr },
        { "raft_layers", "coInt", false, VariantClass::None, nullptr },
        { "reduce_crossing_wall", "coBool", false, VariantClass::None, nullptr },
        { "reduce_fan_stop_start_freq", "coBools", false, VariantClass::None, nullptr },
        { "reduce_infill_retraction_mode", "coEnum", false, VariantClass::None, "Disabled|Auto|Enabled" },
        { "required_nozzle_HRC", "coInts", false, VariantClass::None, nullptr },
        { "resolution", "coFloat", false, VariantClass::None, nullptr },
        { "retract_before_wipe", "coPercents", true, VariantClass::Printer, nullptr },
        { "retract_length_toolchange", "coFloats", true, VariantClass::Printer, nullptr },
        { "retract_lift_above", "coFloats", true, VariantClass::Printer, nullptr },
        { "retract_lift_below", "coFloats", true, VariantClass::Printer, nullptr },
        { "retract_restart_extra", "coFloats", true, VariantClass::Printer, nullptr },
        { "retract_restart_extra_toolchange", "coFloats", true, VariantClass::Printer, nullptr },
        { "retract_when_changing_layer", "coBools", true, VariantClass::Printer, nullptr },
        { "retraction_distances_when_cut", "coFloats", true, VariantClass::Printer, nullptr },
        { "retraction_distances_when_ec", "coFloats", true, VariantClass::Filament, nullptr },
        { "retraction_length", "coFloats", true, VariantClass::Printer, nullptr },
        { "retraction_minimum_travel", "coFloats", true, VariantClass::Printer, nullptr },
        { "retraction_speed", "coFloats", true, VariantClass::Printer, nullptr },
        { "role_base_wipe_speed", "coBool", false, VariantClass::None, nullptr },
        { "scan_first_layer", "coBool", false, VariantClass::None, nullptr },
        { "scarf_angle_threshold", "coInt", false, VariantClass::None, nullptr },
        { "seam_gap", "coPercent", false, VariantClass::None, nullptr },
        { "seam_placement_away_from_overhangs", "coBool", false, VariantClass::None, nullptr },
        { "seam_position", "coEnum", false, VariantClass::None, "nearest|aligned|back|random" },
        { "seam_slope_conditional", "coBool", false, VariantClass::None, nullptr },
        { "seam_slope_entire_loop", "coBool", false, VariantClass::None, nullptr },
        { "seam_slope_gap", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "seam_slope_inner_walls", "coBool", false, VariantClass::None, nullptr },
        { "seam_slope_min_length", "coFloat", false, VariantClass::None, nullptr },
        { "seam_slope_start_height", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "seam_slope_steps", "coInt", false, VariantClass::None, nullptr },
        { "seam_slope_type", "coEnum", false, VariantClass::None, "none|external|all" },
        { "silent_mode", "coBool", false, VariantClass::None, nullptr },
        { "single_extruder_multi_material", "coBool", false, VariantClass::None, nullptr },
        { "skeleton_infill_density", "coPercent", false, VariantClass::None, nullptr },
        { "skeleton_infill_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "skin_infill_density", "coPercent", false, VariantClass::None, nullptr },
        { "skin_infill_depth", "coFloat", false, VariantClass::None, nullptr },
        { "skin_infill_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "skirt_distance", "coFloat", false, VariantClass::None, nullptr },
        { "skirt_height", "coInt", false, VariantClass::None, nullptr },
        { "skirt_loops", "coInt", false, VariantClass::None, nullptr },
        { "skirt_per_object", "coBool", false, VariantClass::None, nullptr },
        { "slice_closing_radius", "coFloat", false, VariantClass::None, nullptr },
        { "slicing_mode", "coEnum", false, VariantClass::None, "regular|even_odd|close_holes" },
        { "slow_down_for_layer_cooling", "coBools", false, VariantClass::None, nullptr },
        { "slow_down_layer_time", "coInts", false, VariantClass::None, nullptr },
        { "slow_down_min_speed", "coFloats", false, VariantClass::Filament, nullptr },
        { "slowdown_end_acc", "coFloats", true, VariantClass::Print, nullptr },
        { "slowdown_end_height", "coFloats", true, VariantClass::Print, nullptr },
        { "slowdown_end_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "slowdown_start_acc", "coFloats", true, VariantClass::Print, nullptr },
        { "slowdown_start_height", "coFloats", true, VariantClass::Print, nullptr },
        { "slowdown_start_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "small_perimeter_speed", "coFloatsOrPercents", true, VariantClass::Print, nullptr },
        { "small_perimeter_threshold", "coFloats", true, VariantClass::Print, nullptr },
        { "smooth_coefficient", "coFloat", false, VariantClass::None, nullptr },
        { "smooth_speed_discontinuity_area", "coBool", false, VariantClass::None, nullptr },
        { "solid_infill_filament", "coInt", false, VariantClass::None, nullptr },
        { "sparse_infill_acceleration", "coFloatsOrPercents", true, VariantClass::Print, nullptr },
        { "sparse_infill_anchor", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "sparse_infill_anchor_max", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "sparse_infill_density", "coPercent", false, VariantClass::None, nullptr },
        { "sparse_infill_filament", "coInt", false, VariantClass::None, nullptr },
        { "sparse_infill_lattice_angle_1", "coFloat", false, VariantClass::None, nullptr },
        { "sparse_infill_lattice_angle_2", "coFloat", false, VariantClass::None, nullptr },
        { "sparse_infill_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "sparse_infill_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "sparse_infill_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "spiral_mode", "coBool", false, VariantClass::None, nullptr },
        { "spiral_mode_max_xy_smoothing", "coFloatOrPercent", false, VariantClass::None, nullptr },
        { "spiral_mode_smooth", "coBool", false, VariantClass::None, nullptr },
        { "standby_temperature_delta", "coInt", false, VariantClass::None, nullptr },
        { "start_end_points", "coPoints", false, VariantClass::None, nullptr },
        { "supertack_plate_temp", "coInts", false, VariantClass::None, nullptr },
        { "supertack_plate_temp_initial_layer", "coInts", false, VariantClass::None, nullptr },
        { "support_air_filtration", "coBool", false, VariantClass::None, nullptr },
        { "support_angle", "coFloat", false, VariantClass::None, nullptr },
        { "support_base_pattern", "coEnum", false, VariantClass::None, "rectilinear|rectilinear-grid|honeycomb|lightning|default|hollow" },
        { "support_base_pattern_spacing", "coFloat", false, VariantClass::None, nullptr },
        { "support_bottom_interface_spacing", "coFloat", false, VariantClass::None, nullptr },
        { "support_bottom_z_distance", "coFloat", false, VariantClass::None, nullptr },
        { "support_chamber_temp_control", "coBool", false, VariantClass::None, nullptr },
        { "support_cooling_filter", "coBool", false, VariantClass::None, nullptr },
        { "support_critical_regions_only", "coBool", false, VariantClass::None, nullptr },
        { "support_expansion", "coFloat", false, VariantClass::None, nullptr },
        { "support_fast_purge_mode", "coBool", false, VariantClass::None, nullptr },
        { "support_filament", "coInt", false, VariantClass::None, nullptr },
        { "support_interface_bottom_layers", "coInt", false, VariantClass::None, nullptr },
        { "support_interface_filament", "coInt", false, VariantClass::None, nullptr },
        { "support_interface_loop_pattern", "coBool", false, VariantClass::None, nullptr },
        { "support_interface_not_for_body", "coBool", false, VariantClass::None, nullptr },
        { "support_interface_pattern", "coEnum", false, VariantClass::None, "auto|rectilinear|concentric|rectilinear_interlaced|grid" },
        { "support_interface_spacing", "coFloat", false, VariantClass::None, nullptr },
        { "support_interface_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "support_interface_top_layers", "coInt", false, VariantClass::None, nullptr },
        { "support_ironing_direction", "coFloat", false, VariantClass::None, nullptr },
        { "support_ironing_flow", "coPercent", false, VariantClass::None, nullptr },
        { "support_ironing_inset", "coFloat", false, VariantClass::None, nullptr },
        { "support_ironing_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "support_ironing_spacing", "coFloat", false, VariantClass::None, nullptr },
        { "support_ironing_speed", "coFloat", false, VariantClass::None, nullptr },
        { "support_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "support_object_first_layer_gap", "coFloat", false, VariantClass::None, nullptr },
        { "support_object_skip_flush", "coBool", false, VariantClass::None, nullptr },
        { "support_object_xy_distance", "coFloat", false, VariantClass::None, nullptr },
        { "support_on_build_plate_only", "coBool", false, VariantClass::None, nullptr },
        { "support_remove_small_overhang", "coBool", false, VariantClass::None, nullptr },
        { "support_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "support_style", "coEnum", false, VariantClass::None, "default|grid|snug|tree_slim|tree_strong|tree_hybrid|tree_organic" },
        { "support_threshold_angle", "coInt", false, VariantClass::None, nullptr },
        { "support_top_z_distance", "coFloat", false, VariantClass::None, nullptr },
        { "support_type", "coEnum", false, VariantClass::None, "normal(auto)|tree(auto)|normal(manual)|tree(manual)" },
        { "symmetric_infill_y_axis", "coBool", false, VariantClass::None, nullptr },
        { "temperature_vitrification", "coInts", false, VariantClass::None, nullptr },
        { "template_custom_gcode", "coString", false, VariantClass::None, nullptr },
        { "textured_plate_temp", "coInts", false, VariantClass::None, nullptr },
        { "textured_plate_temp_initial_layer", "coInts", false, VariantClass::None, nullptr },
        { "thick_bridges", "coBool", false, VariantClass::None, nullptr },
        { "thumbnail_size", "coPoints", false, VariantClass::None, nullptr },
        { "time_lapse_gcode", "coString", false, VariantClass::None, nullptr },
        { "timelapse_type", "coEnum", false, VariantClass::None, "0|1" },
        { "top_area_threshold", "coPercent", false, VariantClass::None, nullptr },
        { "top_color_penetration_layers", "coInt", false, VariantClass::None, nullptr },
        { "top_one_wall_type", "coEnum", false, VariantClass::None, "not apply|all top|topmost" },
        { "top_shell_layers", "coInt", false, VariantClass::None, nullptr },
        { "top_shell_thickness", "coFloat", false, VariantClass::None, nullptr },
        { "top_solid_infill_flow_ratio", "coFloats", false, VariantClass::Print, nullptr },
        { "top_surface_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "top_surface_density", "coPercent", false, VariantClass::None, nullptr },
        { "top_surface_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "top_surface_line_width", "coFloat", false, VariantClass::None, nullptr },
        { "top_surface_pattern", "coEnum", false, VariantClass::None, "concentric|zig-zag|grid|line|cubic|triangles|tri-hexagon|gyroid|honeycomb|adaptivecubic|monotonic|monotonicline|alignedrectilinear|3dhoneycomb|hilbertcurve|archimedeanchords|octagramspiral|supportcubic|lightning|crosshatch|zigzag|crosszag|lockedzag|2dlattice" },
        { "top_surface_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "top_z_overrides_xy_distance", "coBool", false, VariantClass::None, nullptr },
        { "travel_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "travel_jerk", "coFloat", false, VariantClass::None, nullptr },
        { "travel_short_distance_acceleration", "coFloats", true, VariantClass::Print, nullptr },
        { "travel_speed", "coFloats", true, VariantClass::Print, nullptr },
        { "travel_speed_z", "coFloats", true, VariantClass::Print, nullptr },
        { "tree_support_branch_angle", "coFloat", false, VariantClass::None, nullptr },
        { "tree_support_branch_diameter", "coFloat", false, VariantClass::None, nullptr },
        { "tree_support_branch_diameter_angle", "coFloat", false, VariantClass::None, nullptr },
        { "tree_support_branch_distance", "coFloat", false, VariantClass::None, nullptr },
        { "tree_support_wall_count", "coInt", false, VariantClass::None, nullptr },
        { "upward_compatible_machine", "coStrings", false, VariantClass::None, nullptr },
        { "use_firmware_retraction", "coBool", false, VariantClass::None, nullptr },
        { "use_relative_e_distances", "coBool", false, VariantClass::None, nullptr },
        { "vertical_shell_speed", "coFloatsOrPercents", true, VariantClass::Print, nullptr },
        { "volumetric_speed_coefficients", "coStrings", false, VariantClass::Filament, nullptr },
        { "wall_distribution_count", "coInt", false, VariantClass::None, nullptr },
        { "wall_filament", "coInt", false, VariantClass::None, nullptr },
        { "wall_generator", "coEnum", false, VariantClass::None, "classic|arachne" },
        { "wall_loops", "coInt", false, VariantClass::None, nullptr },
        { "wall_sequence", "coEnum", false, VariantClass::None, "inner wall/outer wall|outer wall/inner wall|inner-outer-inner wall" },
        { "wall_transition_angle", "coFloat", false, VariantClass::None, nullptr },
        { "wall_transition_filter_deviation", "coPercent", false, VariantClass::None, nullptr },
        { "wall_transition_length", "coPercent", false, VariantClass::None, nullptr },
        { "wipe", "coBools", true, VariantClass::Printer, nullptr },
        { "wipe_distance", "coFloats", true, VariantClass::Printer, nullptr },
        { "wipe_speed", "coPercent", false, VariantClass::None, nullptr },
        { "wipe_tower_bridging", "coFloat", false, VariantClass::None, nullptr },
        { "wipe_tower_no_sparse_layers", "coBool", false, VariantClass::None, nullptr },
        { "wipe_tower_rotation_angle", "coFloat", false, VariantClass::None, nullptr },
        { "wipe_tower_x", "coFloats", false, VariantClass::None, nullptr },
        { "wipe_tower_y", "coFloats", false, VariantClass::None, nullptr },
        { "wrapping_detection_gcode", "coString", false, VariantClass::None, nullptr },
        { "wrapping_detection_layers", "coInt", false, VariantClass::None, nullptr },
        { "wrapping_exclude_area", "coPoints", false, VariantClass::None, nullptr },
        { "xy_contour_compensation", "coFloat", false, VariantClass::None, nullptr },
        { "xy_hole_compensation", "coFloat", false, VariantClass::None, nullptr },
        { "z_direction_outwall_speed_continuous", "coBool", false, VariantClass::None, nullptr },
        { "z_hop", "coFloats", true, VariantClass::Printer, nullptr },
        { "z_hop_types", "coEnums", true, VariantClass::Printer, "Auto Lift|Normal Lift|Slope Lift|Spiral Lift" },
    };
    return defs;
}

// Our enum values Bambu does not accept as written: key, our value, Bambu value.
// Matched by enumerator name; an empty Bambu value means Bambu has no such enumerator.
const std::vector<EnumTranslation> &generated_enum_translations()
{
    static const std::vector<EnumTranslation> rows = {
        { "bottom_surface_pattern", "rectilinear", "zig-zag" },
        { "bottom_surface_pattern", "quartercubic", "" },
        { "bottom_surface_pattern", "lateral-honeycomb", "" },
        { "bottom_surface_pattern", "lateral-lattice", "" },
        { "bottom_surface_pattern", "tpmsd", "" },
        { "bottom_surface_pattern", "tpmsfk", "" },
        { "bottom_surface_pattern", "default", "" },
        { "brim_type", "painted", "" },
        { "curr_bed_type", "Textured Cool Plate", "" },
        { "curr_bed_type", "Graphic Effect Plate", "" },
        { "ensure_vertical_shell_thickness", "none", "" },
        { "ensure_vertical_shell_thickness", "ensure_critical_only", "" },
        { "ensure_vertical_shell_thickness", "ensure_moderate", "" },
        { "ensure_vertical_shell_thickness", "ensure_all", "" },
        { "host_type", "prusaconnect", "" },
        { "host_type", "crealityprint", "" },
        { "host_type", "esp3d", "" },
        { "host_type", "obico", "" },
        { "host_type", "flashforge", "" },
        { "host_type", "simplyprint", "" },
        { "host_type", "elegoolink", "" },
        { "internal_solid_infill_pattern", "rectilinear", "zig-zag" },
        { "internal_solid_infill_pattern", "quartercubic", "" },
        { "internal_solid_infill_pattern", "lateral-honeycomb", "" },
        { "internal_solid_infill_pattern", "lateral-lattice", "" },
        { "internal_solid_infill_pattern", "tpmsd", "" },
        { "internal_solid_infill_pattern", "tpmsfk", "" },
        { "internal_solid_infill_pattern", "default", "" },
        { "ironing_pattern", "rectilinear", "zig-zag" },
        { "ironing_pattern", "quartercubic", "" },
        { "ironing_pattern", "lateral-honeycomb", "" },
        { "ironing_pattern", "lateral-lattice", "" },
        { "ironing_pattern", "tpmsd", "" },
        { "ironing_pattern", "tpmsfk", "" },
        { "ironing_pattern", "default", "" },
        { "locked_skeleton_infill_pattern", "rectilinear", "zig-zag" },
        { "locked_skeleton_infill_pattern", "quartercubic", "" },
        { "locked_skeleton_infill_pattern", "lateral-honeycomb", "" },
        { "locked_skeleton_infill_pattern", "lateral-lattice", "" },
        { "locked_skeleton_infill_pattern", "tpmsd", "" },
        { "locked_skeleton_infill_pattern", "tpmsfk", "" },
        { "locked_skeleton_infill_pattern", "default", "" },
        { "locked_skin_infill_pattern", "rectilinear", "zig-zag" },
        { "locked_skin_infill_pattern", "quartercubic", "" },
        { "locked_skin_infill_pattern", "lateral-honeycomb", "" },
        { "locked_skin_infill_pattern", "lateral-lattice", "" },
        { "locked_skin_infill_pattern", "tpmsd", "" },
        { "locked_skin_infill_pattern", "tpmsfk", "" },
        { "locked_skin_infill_pattern", "default", "" },
        { "seam_position", "aligned_back", "" },
        { "seam_position", "left", "" },
        { "seam_position", "right", "" },
        { "seam_position", "aligned_front", "" },
        { "sparse_infill_pattern", "rectilinear", "zig-zag" },
        { "sparse_infill_pattern", "quartercubic", "" },
        { "sparse_infill_pattern", "lateral-honeycomb", "" },
        { "sparse_infill_pattern", "lateral-lattice", "" },
        { "sparse_infill_pattern", "tpmsd", "" },
        { "sparse_infill_pattern", "tpmsfk", "" },
        { "sparse_infill_pattern", "default", "" },
        { "support_ironing_pattern", "rectilinear", "zig-zag" },
        { "support_ironing_pattern", "quartercubic", "" },
        { "support_ironing_pattern", "lateral-honeycomb", "" },
        { "support_ironing_pattern", "lateral-lattice", "" },
        { "support_ironing_pattern", "tpmsd", "" },
        { "support_ironing_pattern", "tpmsfk", "" },
        { "support_ironing_pattern", "default", "" },
        { "support_style", "organic", "tree_organic" },
        { "top_surface_pattern", "rectilinear", "zig-zag" },
        { "top_surface_pattern", "quartercubic", "" },
        { "top_surface_pattern", "lateral-honeycomb", "" },
        { "top_surface_pattern", "lateral-lattice", "" },
        { "top_surface_pattern", "tpmsd", "" },
        { "top_surface_pattern", "tpmsfk", "" },
        { "top_surface_pattern", "default", "" },
    };
    return rows;
}

} // namespace BambuExport
} // namespace Slic3r
