"""Bar A for the Z-contouring (ZAA) port.

With zaa_enabled off (the default), a CLI slice of OrcaToleranceTest.stl must be
byte-identical between the head build and the candidate apart from the
"; generated by" timestamp line and the four new "; zaa_* = ..." config lines.
Run on "Bambu Lab P1S 0.4 nozzle" and on "Snapmaker U1 (0.4 nozzle)", each with
offset_layers off and on.

usage: bar_a_zaa.py --base <exe> --cand <exe> [--passes 1]
"""
import argparse
import difflib
import hashlib
import os
import re
import shutil
import subprocess
import sys

T = os.path.dirname(os.path.abspath(__file__))
HUB = r"C:\Users\acesa\AppData\Local\Temp\snorca_hubtest"
SRC_DD = os.path.join(HUB, "dd_lan")
WORK = os.path.join(T, "bar_a_zaa_work")
MODEL = r"C:\Dev\SnapmakerOrcaPhone\resources\handy_models\OrcaToleranceTest.stl"

CASES = [
    ("p1s", "Bambu Lab P1S 0.4 nozzle", "0.20mm Standard @BBL X1C", "Generic PLA", []),
    ("p1s_ofs", "Bambu Lab P1S 0.4 nozzle", "0.20mm Standard @BBL X1C", "Generic PLA",
     ["--offset-layers=1"]),
    ("u1", "Snapmaker U1 (0.4 nozzle)", "0.20 Standard @Snapmaker U1 (0.4 nozzle)", "Snapmaker PLA Basic @U1", []),
    ("u1_ofs", "Snapmaker U1 (0.4 nozzle)", "0.20 Standard @Snapmaker U1 (0.4 nozzle)", "Snapmaker PLA Basic @U1",
     ["--offset-layers=1"]),
]

ZAA_LINE = re.compile(r"^;\s*zaa_(enabled|min_z|minimize_perimeter_height|dont_alternate_fill_direction)\s*=")


def read_lines(path):
    with open(path, encoding="utf-8", errors="replace", newline="") as f:
        return f.readlines()


def strip_ts(lines):
    return [l for l in lines if not l.startswith("; generated by ")]


def strip_zaa(lines):
    return [l for l in lines if not ZAA_LINE.match(l)]


def sha(lines):
    return hashlib.sha256("".join(lines).encode("utf-8", "replace")).hexdigest()


def slice_once(exe, datadir, out, printer, process, filament, extra):
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    cmd = [exe, "--slice", "0", "--allow-newer-file", "--no-thumbnails",
           "--datadir", datadir, "--outputdir", out,
           "--printer-preset", printer,
           "--process-preset", process,
           "--filament-presets", filament] + extra + [MODEL]
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    files = sorted(os.path.join(out, f) for f in os.listdir(out) if f.endswith(".gcode"))
    if p.returncode != 0 or not files:
        sys.stdout.write("slice failed rc=%s\ncmd: %s\nstdout tail:\n%s\nstderr tail:\n%s\n" % (
            p.returncode, " ".join(cmd),
            p.stdout.decode("utf-8", "replace")[-3000:],
            p.stderr.decode("utf-8", "replace")[-3000:]))
        raise SystemExit(2)
    return files[0]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--cand", required=True)
    a = ap.parse_args()

    os.makedirs(WORK, exist_ok=True)
    dds = {}
    for side in ("base", "cand"):
        dd = os.path.join(WORK, "dd_" + side)
        if not os.path.isdir(dd):
            shutil.copytree(SRC_DD, dd)
        dds[side] = dd

    print("base : %s\ncand : %s\nmodel: %s\n" % (a.base, a.cand, MODEL))

    rc = 0
    for name, printer, process, filament, extra in CASES:
        print("--- case %s (%s%s)" % (name, printer, " +offset_layers" if extra else ""))
        bf = slice_once(a.base, dds["base"], os.path.join(WORK, "base", name),
                        printer, process, filament, extra)
        cf = slice_once(a.cand, dds["cand"], os.path.join(WORK, "cand", name),
                        printer, process, filament, extra)

        b = strip_ts(read_lines(bf))
        c = strip_ts(read_lines(cf))

        b_zaa = [l.rstrip("\r\n") for l in b if ZAA_LINE.match(l)]
        c_zaa = [l.rstrip("\r\n") for l in c if ZAA_LINE.match(l)]
        print("    base zaa lines: %d %s" % (len(b_zaa), b_zaa))
        print("    cand zaa lines: %d %s" % (len(c_zaa), c_zaa))

        bs, cs = sha(strip_zaa(b)), sha(strip_zaa(c))
        if bs == cs:
            print("    OK  identical apart from the timestamp and %d zaa_* lines (%d lines)"
                  % (len(c_zaa), len(c)))
            if len(c_zaa) != 4:
                print("    !!  expected exactly 4 zaa_* lines on the candidate")
                rc = 1
            if b_zaa:
                print("    !!  the baseline should carry no zaa_* lines")
                rc = 1
        else:
            rc = 1
            diff = list(difflib.unified_diff(strip_zaa(b), strip_zaa(c), "base", "cand", n=1))
            print("    FAIL  differs; %d diff lines, first 40:" % len(diff))
            for line in diff[:40]:
                sys.stdout.write("      " + (line if line.endswith("\n") else line + "\n"))
        print()

    print("BAR A: %s" % ("PASS" if rc == 0 else "FAIL"))
    return rc


sys.exit(main())
