/**
 * @file SentryWrapper.cpp
 * @brief Opt-in crash reporting (sentry-native + crashpad).
 *
 * What EdgeSlicer does with Sentry, all of it here:
 *   - crashpad always runs and keeps local minidumps (%LOCALAPPDATA%\EdgeSlicer\reports on
 *     Windows) - that is what we debug with, and it sends nothing by itself;
 *   - a crash report is uploaded only when BOTH
 *       (a) this build has a destination: the DSN CI compiles in from the SENTRY_DSN secret
 *           (EDGESLICER_SENTRY_DSN, see CMakeLists.txt), or a tester's "ultra_sentry_dsn" in
 *           the app config, which wins when set; local builds have neither, and
 *       (b) the user switched on Preferences > General > Privacy > "Send crash reports"
 *           (app config "send_crash_reports", default off), enforced through Sentry's own
 *           consent switch so it gates crashpad's uploads as well;
 *   - a report holds the minidump (thread stacks, registers, loaded modules), the app
 *     version as the release, the OS (Sentry's own context) and the most recent warning /
 *     error log lines as breadcrumbs (crashpad keeps two rotating files of 50, so at most
 *     100), each passed through scrub_for_crash_report() before it is stored. No log
 *     files, configs, projects, user id, machine id or host name;
 *   - no usage events, "bury point" logs, sessions or traces are ever sent.
 *
 * When SLIC3R_SENTRY is not defined every function is a no-op.
 */

#include "SentryWrapper.hpp"
#include "SentryScrub.hpp"

#ifdef SLIC3R_SENTRY
#include "sentry.h"
// Generated by CMake into <build>/generated: EDGESLICER_SENTRY_DSN, EDGESLICER_SENTRY_ENVIRONMENT.
#include "edgeslicer_sentry_config.h"
#endif

#ifdef _WIN32
#include <Windows.h>
#include <shlobj.h>
#include <share.h>
#endif

#ifdef __APPLE__
#include <mach-o/dyld.h>
#include <limits.h>
#endif

#include <atomic>
#include <chrono>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <mutex>
#include "common_func/common_func.hpp"

namespace Slic3r {

#ifdef SLIC3R_SENTRY

// A tester's own DSN in the app config ("ultra_sentry_dsn"). Overrides the compiled-in one.
#define EDGE_SENTRY_DSN_OVERRIDE_KEY "ultra_sentry_dsn"
// The "Send crash reports" preference. Absent means off.
#define EDGE_SENTRY_CONSENT_KEY "send_crash_reports"
// Must match the release CI creates when it uploads the debug symbols
// (.github/workflows: "edgeslicer@<Snapmaker_VERSION>").
#define EDGE_SENTRY_RELEASE "edgeslicer@" Snapmaker_VERSION

namespace {

// ---- event scrubbing ------------------------------------------------------------------------

void scrub_string_key(sentry_value_t obj, const char* key)
{
    sentry_value_t v = sentry_value_get_by_key(obj, key);
    if (sentry_value_get_type(v) != SENTRY_VALUE_TYPE_STRING)
        return;
    const char* s = sentry_value_as_string(v);
    sentry_value_set_by_key(obj, key, sentry_value_new_string(scrub_for_crash_report(s ? s : "", 4096).c_str()));
}

void scrub_list_items(sentry_value_t list, const char* key)
{
    if (sentry_value_get_type(list) != SENTRY_VALUE_TYPE_LIST)
        return;
    const size_t n = sentry_value_get_length(list);
    for (size_t i = 0; i < n; ++i)
        scrub_string_key(sentry_value_get_by_index(list, i), key);
}

// Removes the fields that could identify a person or a machine. Cheap, no allocation of note:
// safe to run from the crash hook.
void strip_identity(sentry_value_t event)
{
    sentry_value_remove_by_key(event, "user");
    sentry_value_remove_by_key(event, "server_name");
    sentry_value_remove_by_key(event, "request");
    sentry_value_remove_by_key(event, "extra"); // free-form, cannot be walked key by key here
}

// Every text field of a (non-crash) event through the scrubber. Breadcrumbs are already
// scrubbed when they are added; doing it again costs little and covers any added elsewhere.
void scrub_event(sentry_value_t event)
{
    strip_identity(event);

    sentry_value_t msg = sentry_value_get_by_key(event, "message");
    if (sentry_value_get_type(msg) == SENTRY_VALUE_TYPE_STRING)
        scrub_string_key(event, "message");
    else if (sentry_value_get_type(msg) == SENTRY_VALUE_TYPE_OBJECT) {
        scrub_string_key(msg, "formatted");
        scrub_string_key(msg, "message");
    }
    sentry_value_t logentry = sentry_value_get_by_key(event, "logentry");
    if (sentry_value_get_type(logentry) == SENTRY_VALUE_TYPE_OBJECT) {
        scrub_string_key(logentry, "formatted");
        scrub_string_key(logentry, "message");
    }
    sentry_value_t exc = sentry_value_get_by_key(event, "exception");
    if (sentry_value_get_type(exc) == SENTRY_VALUE_TYPE_OBJECT)
        scrub_list_items(sentry_value_get_by_key(exc, "values"), "value");
    else
        scrub_list_items(exc, "value");

    sentry_value_t crumbs = sentry_value_get_by_key(event, "breadcrumbs");
    if (sentry_value_get_type(crumbs) == SENTRY_VALUE_TYPE_OBJECT)
        scrub_list_items(sentry_value_get_by_key(crumbs, "values"), "message");
    else
        scrub_list_items(crumbs, "message");
}

sentry_value_t before_send(sentry_value_t event, void* /*hint*/, void* /*user_data*/)
{
    scrub_event(event);
    return event;
}

// Runs inside the crashed process (Windows: from the unhandled-exception filter; never on
// macOS with crashpad). With crashpad the event handed in is nearly empty - the stack comes
// from the minidump - so no regex work here: a crashed heap is no place for it. The scope that
// crashpad merges in afterwards carries only our release/environment/tags and the breadcrumbs,
// which were scrubbed when they were added.
sentry_value_t on_crash(const sentry_ucontext_t* /*uctx*/, sentry_value_t event, void* /*closure*/)
{
    strip_identity(event);
    return event;
}

// EDGESLICER_SENTRY_DEBUG=<file>: sentry-native's own diagnostics go to that file. For testing
// the pipeline against a local listener; says nothing about the user.
FILE* g_debug_log = nullptr;

void debug_logger(sentry_level_t level, const char* message, va_list args, void* /*userdata*/)
{
    if (g_debug_log == nullptr)
        return;
    std::fprintf(g_debug_log, "[sentry %d] ", int(level));
    std::vfprintf(g_debug_log, message, args);
    std::fputc('\n', g_debug_log);
    std::fflush(g_debug_log);
}

// Where crashpad keeps its database (pending reports, local minidumps, the consent file).
// An instance started with --datadir keeps its own, inside that directory, so a test or
// portable instance never shares crash state with the regular install.
std::filesystem::path sentry_database_dir()
{
    if (const std::string over = common::datadir_override(); !over.empty()) {
#ifdef _WIN32
        return std::filesystem::u8path(over) / "SentryData";
#else
        return std::filesystem::path(over) / "SentryData";
#endif
    }
#ifdef _WIN32
    PWSTR psz = nullptr;
    std::filesystem::path dir;
    if (SUCCEEDED(SHGetKnownFolderPath(FOLDERID_LocalAppData, 0, nullptr, &psz)) && psz != nullptr)
        dir = std::filesystem::path(psz) / SLIC3R_APP_KEY;
    else {
        wchar_t tmp[MAX_PATH + 1] = {0};
        if (GetTempPathW(MAX_PATH, tmp) != 0)
            dir = std::filesystem::path(tmp) / SLIC3R_APP_KEY;
    }
    if (psz != nullptr)
        CoTaskMemFree(psz);
    return dir;
#elif __APPLE__
    const char* home = getenv("HOME");
    if (home == nullptr || *home == '\0')
        return {};
    return std::filesystem::path(home) / "Library" / "Application Support" / SLIC3R_APP_KEY / "SentryData";
#else
    return {}; // sentry-native's default (.sentry-native in the working directory)
#endif
}

std::filesystem::path crashpad_handler_path()
{
#ifdef _WIN32
    std::wstring buf(32768, L'\0');
    const DWORD  n = ::GetModuleFileNameW(nullptr, &buf[0], DWORD(buf.size()));
    if (n == 0 || n >= buf.size())
        return {};
    buf.resize(n);
    return std::filesystem::path(buf).parent_path() / L"crashpad_handler.exe";
#elif __APPLE__
    char     exe[PATH_MAX] = {0};
    uint32_t size          = sizeof(exe);
    if (_NSGetExecutablePath(exe, &size) != 0)
        return {};
    return std::filesystem::path(exe).parent_path() / "crashpad_handler";
#else
    return {};
#endif
}

#ifdef _WIN32
// sentry_init must not take the process down if crashpad cannot start; C-style so __try works.
extern "C" {
static int safe_sentry_init(sentry_options_t* options)
{
    int result = -1;
    __try {
        result = sentry_init(options);
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        result = -1;
    }
    return result;
}
}
#endif

// Log lines that became breadcrumbs, for the rate limit below.
std::mutex g_crumb_mutex;

} // namespace

void initSentryEx()
{
    // (a) the destination. The config override exists so a crash report can be tested
    // against a local listener or a personal project without rebuilding.
    std::string dsn = common::get_app_config_string(EDGE_SENTRY_DSN_OVERRIDE_KEY);
    if (dsn.empty())
        dsn = EDGESLICER_SENTRY_DSN;
    const bool available = !dsn.empty();
    set_crash_reports_available(available);

    // (b) consent: off unless the saved preference says otherwise. This is read here, before
    // the GUI exists, so there is no window in which consent is on by default.
    const bool consent = available && common::get_app_config_bool(EDGE_SENTRY_CONSENT_KEY, false);

    sentry_options_t* options = sentry_options_new();
    if (available)
        sentry_options_set_dsn(options, dsn.c_str());
    // Always require consent: it is the one switch sentry checks before crashpad may upload a
    // minidump AND before any envelope leaves, and it is what lets the preference turn uploads
    // off again at runtime.
    sentry_options_set_require_user_consent(options, 1);

    const std::filesystem::path db_dir  = sentry_database_dir();
    const std::filesystem::path handler = crashpad_handler_path();
#ifdef _WIN32
    if (!handler.empty())
        sentry_options_set_handler_pathw(options, handler.wstring().c_str());
    if (!db_dir.empty())
        sentry_options_set_database_pathw(options, db_dir.wstring().c_str());
#else
    if (!handler.empty())
        sentry_options_set_handler_path(options, handler.string().c_str());
    if (!db_dir.empty())
        sentry_options_set_database_path(options, db_dir.string().c_str());
#endif
    // sentry-native persists consent in <database>/user-consent and loads it during init. Our
    // preference is the only source of truth: drop the file so a "given" left by an earlier
    // run can never count before the explicit give/revoke below.
    if (!db_dir.empty()) {
        std::error_code ec;
        std::filesystem::remove(db_dir / "user-consent", ec);
    }

    if (const char* dbg = std::getenv("EDGESLICER_SENTRY_DEBUG"); dbg != nullptr && *dbg != '\0') {
#ifdef _WIN32
        g_debug_log = _fsopen(dbg, "a", _SH_DENYNO);
#else
        g_debug_log = std::fopen(dbg, "a");
#endif
        sentry_options_set_debug(options, 1);
        sentry_options_set_logger(options, debug_logger, nullptr);
    } else {
        sentry_options_set_debug(options, 0);
    }

    sentry_options_set_release(options, EDGE_SENTRY_RELEASE);
    sentry_options_set_environment(options, EDGESLICER_SENTRY_ENVIRONMENT);

    // Crashes only: no sessions (release health), no traces, no structured logs.
    sentry_options_set_auto_session_tracking(options, 0);
    sentry_options_set_sample_rate(options, 1.0);
    sentry_options_set_traces_sample_rate(options, 0.0);
    sentry_options_set_enable_logs(options, 0);
    // Frames are symbolicated by Sentry from the symbols CI uploads, not on the user's machine.
    sentry_options_set_symbolize_stacktraces(options, 0);
    sentry_options_set_max_breadcrumbs(options, 50);
    sentry_options_set_before_send(options, before_send, nullptr);
    sentry_options_set_on_crash(options, on_crash, nullptr);
    // No attachments: log files and configs are never sent.

#ifdef _WIN32
    const int result = safe_sentry_init(options);
    if (result != 0) {
        // sentry_init frees the options itself, except when it faulted before getting that far.
        set_sentry_flags(false);
        return;
    }
#else
    if (sentry_init(options) != 0) {
        set_sentry_flags(false);
        return;
    }
#endif

    if (consent)
        sentry_user_consent_give();
    else
        sentry_user_consent_revoke();
    set_sentry_flags(true);

    sentry_set_tag("app_version", Snapmaker_VERSION);
}

void exitSentryEx()
{
    if (get_sentry_flags()) {
        sentry_close();
        set_sentry_flags(false);
    }
    if (g_debug_log != nullptr) {
        std::fclose(g_debug_log);
        g_debug_log = nullptr;
    }
}

void setSentryUserConsentEx(bool agreed)
{
    if (!get_sentry_flags())
        return;
    // Without a destination there is nothing to consent to; crashpad keeps dumps locally.
    if (agreed && get_crash_reports_available())
        sentry_user_consent_give();
    else
        sentry_user_consent_revoke();
}

void sentryAddLogBreadcrumbEx(int boost_severity, const std::string& message)
{
    // boost::log::trivial: 0 trace, 1 debug, 2 info, 3 warning, 4 error, 5 fatal
    if (boost_severity < 3 || !get_sentry_flags() || sentry_user_consent_get() != SENTRY_USER_CONSENT_GIVEN)
        return;

    // At most 20 lines a second: a log flood must not turn into a disk-write flood (crashpad
    // writes every breadcrumb to its run folder) or burn the logging thread on scrubbing.
    {
        static auto window_start = std::chrono::steady_clock::now();
        static int  in_window    = 0;
        std::lock_guard<std::mutex> lock(g_crumb_mutex);
        const auto now = std::chrono::steady_clock::now();
        if (now - window_start > std::chrono::seconds(1)) {
            window_start = now;
            in_window    = 0;
        }
        if (++in_window > 20)
            return;
    }

    const std::string clean = scrub_for_crash_report(message, 512);
    const char*       level = boost_severity >= 5 ? "fatal" : boost_severity == 4 ? "error" : "warning";

    sentry_value_t crumb = sentry_value_new_breadcrumb("default", clean.c_str());
    sentry_value_set_by_key(crumb, "category", sentry_value_new_string("log"));
    sentry_value_set_by_key(crumb, "level", sentry_value_new_string(level));
    // crashpad's breadcrumb file writer is not thread-safe on its own.
    std::lock_guard<std::mutex> lock(g_crumb_mutex);
    sentry_add_breadcrumb(crumb);
}

#endif // SLIC3R_SENTRY

void initSentry()
{
#ifdef SLIC3R_SENTRY
    initSentryEx();
#endif
}

void exitSentry()
{
#ifdef SLIC3R_SENTRY
    exitSentryEx();
#endif
}

void setSentryUserConsent(bool agreed)
{
#ifdef SLIC3R_SENTRY
    setSentryUserConsentEx(agreed);
#else
    (void) agreed;
#endif
}

bool sentryCrashReportsAvailable()
{
#ifdef SLIC3R_SENTRY
    return get_crash_reports_available();
#else
    return false;
#endif
}

bool sentryCrashedLastRun(bool clear)
{
#ifdef SLIC3R_SENTRY
    if (!get_sentry_flags())
        return false;
    const int crashed = sentry_get_crashed_last_run();
    if (clear)
        sentry_clear_crashed_last_run();
    return crashed == 1;
#else
    (void) clear;
    return false;
#endif
}

void sentryAddLogBreadcrumb(int boost_severity, const std::string& message)
{
#ifdef SLIC3R_SENTRY
    sentryAddLogBreadcrumbEx(boost_severity, message);
#else
    (void) boost_severity;
    (void) message;
#endif
}

void sentryReportLog(SENTRY_LOG_LEVEL   logLevel,
    const std::string& logContent,
    const std::string& funcModule,
    const std::string& logTagKey,
    const std::string& logTagValue,
    const std::string& logTraceId)
{
    // Deliberately nothing: EdgeSlicer sends crash reports only (see the file comment).
    (void) logLevel;
    (void) logContent;
    (void) funcModule;
    (void) logTagKey;
    (void) logTagValue;
    (void) logTraceId;
}

void set_sentry_tags(const std::string& tag_key, const std::string& tag_value)
{
#ifdef SLIC3R_SENTRY
    if (get_sentry_flags() && !tag_key.empty())
        sentry_set_tag(tag_key.c_str(), scrub_for_crash_report(tag_value, 200).c_str());
#else
    (void) tag_key;
    (void) tag_value;
#endif
}

} // namespace Slic3r
